agent:
  type: naive
remember_cot: True
self_refine_max_iterations: 3

prompt_builder_strategy: history
prompt_builder_config:
  history: True
  max_history: 16
  max_image_history: 0
  max_cot_history: 1
  
