client:
  model_id: gemini-1.5-flash
  base_url: https://spotty-toys-teach.loca.lt/v1
  api_key: AIzaSyCoyHxTwdxuRJjeMVMclJJdmCUDRkMmp-0
  is_chat_model: True
  generate_kwargs:
    temperature: 0.5
  timeout: 60