agent: 
  type: naive
  remember_cot: True
  max_history: 16
  max_image_history: 0
  max_cot_history: 1

eval:
  num_workers: 1
  num_episodes:
    nle: 5
    minihack: 5
    babyai: 25
    crafter: 5
    babaisai: 5
    textworld: 20
  max_steps_per_episode: null
  save_trajectories: True

  wandb_save: False
  wandb:
    project_name: benchmark
    entity_name: ICLbench

client:
  client_name: openai
  model_id: gpt-4o
  base_url: https://spotty-toys-teach.loca.lt/v1
  is_chat_model: True
  generate_kwargs:
    temperature: 0.0
    max_tokens: 1024
  timeout: 60


envs:
  names: nle
  env_kwargs:
    seed: null
  nle_kwargs:
    character: "@"
    max_episode_steps: 100_000
    no_progress_timeout: 150
    savedir: null
    save_ttyrec_every: 0
  minihack_kwargs: {}
  babyai_kwargs:
    num_dists: 0
  crafter_kwargs: {}
  craftax_kwargs: {}
  textworld_kwargs:
    objective: True
    description: True
    score: True
    max_score: True
    won: True
    max_episode_steps: 80
    textworld_games_path: tw_games
  babaisai_kwargs: 
    add_ruleset: True

tasks:
  nle_tasks:
    - NetHackChallenge-v0

  minihack_tasks:
    - "MiniHack-Boxoban-Hard-v0"
    - "MiniHack-Boxoban-Medium-v0"
    - "MiniHack-Corridor-R3-v0"
    - "MiniHack-CorridorBattle-Dark-v0"
    - "MiniHack-Quest-Easy-v0"
    - "MiniHack-Quest-Medium-v0"
    - "MiniHack-Quest-Hard-v0"

  crafter_tasks:
    - "default"

  craftax_tasks:
    - "Craftax-Symbolic-v1"

  babyai_tasks:
    - "BabyAI-MixedTrainLocal-v0/goto"
    - "BabyAI-MixedTrainLocal-v0/pickup"
    - "BabyAI-MixedTrainLocal-v0/open"
    - "BabyAI-MixedTrainLocal-v0/putnext"
    - "BabyAI-MixedTrainLocal-v0/pick_up_seq_go_to"

  textworld_tasks:
    - "treasure_hunter"
    - "the_cooking_game"
    - "coin_collector"

  babaisai_tasks:
    - "env/make_win-distr_obj_rule"
    - "env/goto_win-distr_obj_rule"
    - "env/goto_win"
    - "env/goto_win-distr_obj"
    - "env/goto_win-distr_rule"
    - "env/goto_win-distr_obj-irrelevant_rule"
    - "env/goto_win-distr_win_rule"
    - "env/make_win-distr_obj"
    - "env/make_win-distr_rule"
    - "env/make_win"
    - "env/make_win-distr_obj-irrelevant_rule"
    - "env/two_room-goto_win"
    - "env/two_room-goto_win-distr_obj_rule"
    - "env/two_room-goto_win-distr_rule"
    - "env/two_room-goto_win-distr_obj"
    - "env/two_room-goto_win-distr_obj-irrelevant_rule"
    - "env/two_room-goto_win-distr_win_rule"
    - "env/two_room-break_stop-goto_win-distr_obj_rule"
    - "env/two_room-break_stop-goto_win-distr_obj"
    - "env/two_room-break_stop-goto_win-distr_rule"
    - "env/two_room-break_stop-goto_win-distr_obj-irrelevant_rule"
    - "env/two_room-break_stop-goto_win"
    - "env/two_room-maybe_break_stop-goto_win-distr_obj_rule"
    - "env/two_room-maybe_break_stop-goto_win"
    - "env/two_room-maybe_break_stop-goto_win-distr_obj"
    - "env/two_room-maybe_break_stop-goto_win-distr_rule"
    - "env/two_room-maybe_break_stop-goto_win-distr_obj-irrelevant_rule"
    - "env/two_room-make_win-distr_obj_rule"
    - "env/two_room-make_win-distr_rule"
    - "env/two_room-make_win"
    - "env/two_room-make_win-distr_obj-irrelevant_rule"
    - "env/two_room-make_win-distr_obj"
    - "env/two_room-make_win-distr_win_rule"
    - "env/two_room-break_stop-make_win-distr_obj_rule"
    - "env/two_room-break_stop-make_win-distr_rule"
    - "env/two_room-break_stop-make_win"
    - "env/two_room-break_stop-make_win-distr_obj-irrelevant_rule"
    - "env/two_room-break_stop-make_win-distr_obj"
    - "env/two_room-make_you"
    - "env/two_room-make_you-make_win"
    - "env/two_room-make_wall_win"

hydra:
  run:
    dir: ./results/${now:%Y-%m-%d}/${now:%H-%M-%S}