env_names: babyai

env_kwargs:
  seed: null

nle_kwargs:
  character: "@"
  max_episode_steps: 100_000
  no_progress_timeout: 150
  savedir: null
  save_ttyrec_every: 0

minihack_kwargs: {}

babyai_kwargs:
  num_dists: 0

craftax_kwargs: {}

textworld_kwargs:
  objective: True
  description: True
  score: True
  max_score: True
  won: True
  max_episode_steps: 80
  textworld_games_path: tw_games

babaisai_kwargs: 
  add_ruleset: True

vlm: True
