env_names: babyai
env_kwargs:
  prompt_mode: hybrid
  seed: null

babyai_kwargs:
  num_dists: 0

textworld_kwargs:
  objective: True
  description: True
  max_episode_steps: 40

language: True
ascii_map: False
vlm: False