env_names: minihack
env_kwargs:
  seed: null

babyai_kwargs:
  num_dists: 0

craftax_kwargs: {}

textworld_kwargs:
  objective: True
  description: True
  score: True
  max_score: True
  won: True
  max_episode_steps: 80
  textworld_games_path: tw_games

vlm: True