model_id: "/root/gemma-2b"
peft_model_id: "/root/gemma-2b_lora/checkpoint-100000"

wandb: False

savedir: "./"
max_games: 10
max_steps: 100000 # Max steps per game
max_seq_length: 8192
fp16: false
bf16: true
report_to: "wandb"

###### SAMPLING PARAMETERS #######
temperature: 0.95
top_p: 0.95
num_return_sequences: 1
num_tries: 1
do_sample: True

prompt_builder: "human"
max_length: 16000
max_history: 16
summary_prompt: "lawful dwarven Valkyrie"

use_lora: true
lora:
  alpha: 32
  dropout: 0.05
  r: 16