# Model and server settings
base_url: https://rich-ravens-joke.loca.lt/v1

# Agent settings
model_id: meta-llama/Meta-Llama-3.1-8B-Instruct

# Agent settings:
# - naive: agent that always takes the first action
# - react: 
# - reflexion:
# - guidebook:
agent: naive


# Prompt builder settings
prompt_builder_strategy: history
prompt_builder_config:
  history: True #
  max_history: 128
  simple: False # TODO: If True the history will only contain previous messages and actions, no maps
  diff: False
  vlm: False
  
  max_length: 128000


# Environment settings
# if testing on multiple environments, separate the env_names with commas
env_names: minihack
# The options for the game observations are:
# - language: simple language observations (~100 tokens per obs)
# - ascii_map: only the ascii map (no colors) (~375 tokens per obs)
# - hybrid: language observations and ascii map (~450 tokens per obs)
# - vlm: image observations, potentially with language description
env_kwargs:
  prompt_mode: hybrid
language: True
ascii_map: False
vlm: False

# Evaluation settings
num_episodes: 1
num_workers: 1
max_steps_per_episode: 1000

# Generation settings
generate_kwargs:
  temperature: 0.25
  top_p: 0.95
  n: 10

savedir: ./outputs