env_kwargs:
  prompt_mode: language
savedir: null
prompt_builder_strategy: chat
model_id: microsoft/Phi-3-mini-128k-instruct 
url: http://localhost:8000/v1/chat/completions
generate_kwargs:
  temperature: 0.8
  top_p: 0.95
  n: 10
num_runs: 1
num_workers: 1