dataset_path: "/root/fmrl/human_dataset.hf"
model_id: "/root/Phi-3-vision-128k-instruct"
output_dir: "models"
per_device_train_batch_size: 16
gradient_accumulation_steps: 1
save_steps: 25000
logging_steps: 100
learning_rate: 1.5e-5
max_seq_length: 8192
fp16: true
bf16: false
gradient_checkpointing: false
num_train_epochs: 5
weight_decay: 0.001
warmup_steps: 50
lr_scheduler_type: "linear"
report_to: "wandb"
DDP: false # If true, run it with python -m torch.distributed.launch --nnodes=1 --nproc_per_node=2 finetune_accelerate.py
use_lora: false
lora_alpha: 32
lora_dropout: 0.05
r: 16