from nle import nethack as nh

obj_classes = {getattr(nh, x): x for x in dir(nh) if x.endswith("_CLASS")}
glyph_classes = sorted((getattr(nh, x), x) for x in dir(nh) if x.endswith("_OFF"))

ALL_PETS = [nh.GLYPH_PET_OFF + i for i in range(nh.NUMMONS)]

print(nh.GLYPH_MON_OFF)
print(nh.GLYPH_PET_OFF)
print(nh.GLYPH_OBJ_OFF)

# PETS_TO_GLYPH = defaultdict(list)

# for i in ALL_PETS:
#     # Pets have a color offset of 16
#     mon = nh.permonst(nh.glyph_to_mon(i))
#     print(f"{i} | {mon.mname} | {mon.mcolor+16} | {nh.GLYPH_PET_OFF + i}")
#     PETS_TO_GLYPH

# TODO: MISSING PETS

# print("*_NOTE: Auto-generated by `gen_nle_docs_glyphs.py`_*")
# print("")

# print("## Glyph classes")
# print("")
# print(glyph_classes)

# print("")
# print("## Object classes")
# print("")
# print(obj_classes)


# print("")
# print("## Detailed Glyph Table")
# print("")
# print("| Glyph | Class | Description | (Optional) Subclass")
# print("| ----- | ----- | -------- | ----------- |")
# last_cls = ""
for i in range(nh.MAX_GLYPH):
    desc = ""
    if glyph_classes and i == glyph_classes[0][0]:
        cls = glyph_classes.pop(0)[1].replace("_OFF", "")

    if cls != "GLYPH_MON" and cls != "GLYPH_OBJ" and cls == last_cls:
        pass
    else:
        if nh.glyph_is_monster(i):
            desc = f'"{nh.permonst(nh.glyph_to_mon(i)).mname}" | '

        # if nh.glyph_is_normal_object(i):
        #     obj = nh.objclass(nh.glyph_to_obj(i))
        #     appearance = nh.OBJ_DESCR(obj) or nh.OBJ_NAME(obj)
        #     oclass = ord(obj.oc_class)
        #     desc = f'"{appearance}" | {obj_classes[oclass]}'

        # print(f"| {i} | {cls} | {desc} |")

        # if cls != "GLYPH_MON" and cls != "GLYPH_OBJ":
        #     print(f"| ... | ... | --More-- |  |")

    last_cls = cls


obj_class_types = {
    "RANDOM_CLASS": 0,
    "ILLOBJ_CLASS": 1,
    "WEAPON_CLASS": 2,
    "ARMOR_CLASS": 3,
    "RING_CLASS": 4,
    "AMULET_CLASS": 5,
    "TOOL_CLASS": 6,
    "FOOD_CLASS": 7,
    "POTION_CLASS": 8,
    "SCROLL_CLASS": 9,
    "SPBOOK_CLASS": 10,
    "WAND_CLASS": 11,
    "COIN_CLASS": 12,
    "GEM_CLASS": 13,
    "ROCK_CLASS": 14,
    "BALL_CLASS": 15,
    "CHAIN_CLASS": 16,
    "VENOM_CLASS": 17,
    "MAXOCLASSES": 18,
}

obj_class_symbols = {
    "COIN_CLASS": "$",
    "ILLOBJ_CLASS": "]",
    "WEAPON_CLASS": ")",
    "ARMOR_CLASS": "[",
    "RING_CLASS": "=",
    "AMULET_CLASS": '"',
    "TOOL_CLASS": "(",
    "FOOD_CLASS": "%",
    "POTION_CLASS": "!",
    "SCROLL_CLASS": "?",
    "SPBOOK_CLASS": "+",
    "WAND_CLASS": "/",
    "GOLD_CLASS": "$",
    "GEM_CLASS": "*",
    "ROCK_CLASS": "`",
    "BALL_CLASS": "0",
    "CHAIN_CLASS": "_",
    "VENOM_CLASS": ".",
}

color_dict = {
    0: "CLR_BLACK",
    1: "CLR_RED",
    2: "CLR_GREEN",
    3: "CLR_BROWN",
    4: "CLR_BLUE",
    5: "CLR_MAGENTA",
    6: "CLR_CYAN",
    7: "CLR_GRAY",
    8: "NO_COLOR",
    9: "CLR_ORANGE",
    10: "CLR_BRIGHT_GREEN",
    11: "CLR_YELLOW",
    12: "CLR_BRIGHT_BLUE",
    13: "CLR_BRIGHT_MAGENTA",
    14: "CLR_BRIGHT_CYAN",
    15: "CLR_WHITE",
}

pet_color_dict = {
    16: "PET_CLR_BLACK",
    17: "PET_CLR_RED",
    18: "PET_CLR_GREEN",
    19: "PET_CLR_BROWN",
    20: "PET_CLR_BLUE",
    21: "PET_CLR_MAGENTA",
    22: "PET_CLR_CYAN",
    23: "PET_CLR_GRAY",
    24: "PET_NO_COLOR",
    25: "PET_CLR_ORANGE",
    26: "PET_CLR_BRIGHT_GREEN",
    27: "PET_CLR_YELLOW",
    28: "PET_CLR_BRIGHT_BLUE",
    29: "PET_CLR_BRIGHT_MAGENTA",
    30: "PET_CLR_BRIGHT_CYAN",
    31: "PET_CLR_WHITE",
}


from collections import defaultdict

OBJ_TO_GLYPH_DICT = defaultdict(list)

for i in range(nh.MAX_GLYPH):
    if nh.glyph_is_normal_object(i):
        obj = nh.objclass(nh.glyph_to_obj(i))
        appearance = nh.OBJ_DESCR(obj) or nh.OBJ_NAME(obj)
        oclass = ord(obj.oc_class)
        desc = f"{i} | {obj_classes[oclass]} | {appearance} | {obj_class_symbols[obj_classes[oclass]]} | {color_dict[obj.oc_color]}"
        OBJ_TO_GLYPH_DICT[
            (obj_class_symbols[obj_classes[oclass]], color_dict[obj.oc_color])
        ].append({"glyph": i, "appearance": appearance, "class": obj_classes[oclass]})


OBJ_TO_GLYPH = {
    ("]", "CLR_BLACK"): [
        {"glyph": 1906, "appearance": "strange object", "class": "ILLOBJ_CLASS"}
    ],
    (")", "CLR_CYAN"): [
        {"glyph": 1907, "appearance": "arrow", "class": "WEAPON_CLASS"},
        {"glyph": 1911, "appearance": "bamboo arrow", "class": "WEAPON_CLASS"},
        {"glyph": 1912, "appearance": "crossbow bolt", "class": "WEAPON_CLASS"},
        {"glyph": 1913, "appearance": "dart", "class": "WEAPON_CLASS"},
        {"glyph": 1914, "appearance": "throwing star", "class": "WEAPON_CLASS"},
        {"glyph": 1916, "appearance": "spear", "class": "WEAPON_CLASS"},
        {"glyph": 1919, "appearance": "stout spear", "class": "WEAPON_CLASS"},
        {"glyph": 1921, "appearance": "throwing spear", "class": "WEAPON_CLASS"},
        {"glyph": 1922, "appearance": "trident", "class": "WEAPON_CLASS"},
        {"glyph": 1923, "appearance": "dagger", "class": "WEAPON_CLASS"},
        {"glyph": 1927, "appearance": "athame", "class": "WEAPON_CLASS"},
        {"glyph": 1928, "appearance": "scalpel", "class": "WEAPON_CLASS"},
        {"glyph": 1929, "appearance": "knife", "class": "WEAPON_CLASS"},
        {"glyph": 1930, "appearance": "stiletto", "class": "WEAPON_CLASS"},
        {"glyph": 1933, "appearance": "axe", "class": "WEAPON_CLASS"},
        {"glyph": 1934, "appearance": "double-headed axe", "class": "WEAPON_CLASS"},
        {"glyph": 1935, "appearance": "short sword", "class": "WEAPON_CLASS"},
        {"glyph": 1938, "appearance": "broad short sword", "class": "WEAPON_CLASS"},
        {"glyph": 1939, "appearance": "curved sword", "class": "WEAPON_CLASS"},
        {"glyph": 1941, "appearance": "broadsword", "class": "WEAPON_CLASS"},
        {"glyph": 1943, "appearance": "long sword", "class": "WEAPON_CLASS"},
        {"glyph": 1944, "appearance": "two-handed sword", "class": "WEAPON_CLASS"},
        {"glyph": 1945, "appearance": "samurai sword", "class": "WEAPON_CLASS"},
        {"glyph": 1946, "appearance": "long samurai sword", "class": "WEAPON_CLASS"},
        {"glyph": 1948, "appearance": "vulgar polearm", "class": "WEAPON_CLASS"},
        {"glyph": 1949, "appearance": "hilted polearm", "class": "WEAPON_CLASS"},
        {"glyph": 1950, "appearance": "forked polearm", "class": "WEAPON_CLASS"},
        {"glyph": 1951, "appearance": "single-edged polearm", "class": "WEAPON_CLASS"},
        {"glyph": 1952, "appearance": "lance", "class": "WEAPON_CLASS"},
        {"glyph": 1953, "appearance": "angled poleaxe", "class": "WEAPON_CLASS"},
        {"glyph": 1954, "appearance": "long poleaxe", "class": "WEAPON_CLASS"},
        {"glyph": 1955, "appearance": "pole cleaver", "class": "WEAPON_CLASS"},
        {"glyph": 1956, "appearance": "broad pick", "class": "WEAPON_CLASS"},
        {"glyph": 1957, "appearance": "pole sickle", "class": "WEAPON_CLASS"},
        {"glyph": 1958, "appearance": "pruning hook", "class": "WEAPON_CLASS"},
        {"glyph": 1959, "appearance": "hooked polearm", "class": "WEAPON_CLASS"},
        {"glyph": 1960, "appearance": "pronged polearm", "class": "WEAPON_CLASS"},
        {"glyph": 1961, "appearance": "beaked polearm", "class": "WEAPON_CLASS"},
        {"glyph": 1962, "appearance": "mace", "class": "WEAPON_CLASS"},
        {"glyph": 1963, "appearance": "morning star", "class": "WEAPON_CLASS"},
        {"glyph": 1964, "appearance": "war hammer", "class": "WEAPON_CLASS"},
        {"glyph": 1968, "appearance": "thonged club", "class": "WEAPON_CLASS"},
        {"glyph": 1969, "appearance": "flail", "class": "WEAPON_CLASS"},
    ],
    (")", "CLR_BROWN"): [
        {"glyph": 1908, "appearance": "runed arrow", "class": "WEAPON_CLASS"},
        {"glyph": 1915, "appearance": "boomerang", "class": "WEAPON_CLASS"},
        {"glyph": 1917, "appearance": "runed spear", "class": "WEAPON_CLASS"},
        {"glyph": 1924, "appearance": "runed dagger", "class": "WEAPON_CLASS"},
        {"glyph": 1936, "appearance": "runed short sword", "class": "WEAPON_CLASS"},
        {"glyph": 1942, "appearance": "runed broadsword", "class": "WEAPON_CLASS"},
        {"glyph": 1965, "appearance": "club", "class": "WEAPON_CLASS"},
        {"glyph": 1966, "appearance": "rubber hose", "class": "WEAPON_CLASS"},
        {"glyph": 1967, "appearance": "staff", "class": "WEAPON_CLASS"},
        {"glyph": 1970, "appearance": "bullwhip", "class": "WEAPON_CLASS"},
        {"glyph": 1971, "appearance": "bow", "class": "WEAPON_CLASS"},
        {"glyph": 1972, "appearance": "runed bow", "class": "WEAPON_CLASS"},
        {"glyph": 1974, "appearance": "long bow", "class": "WEAPON_CLASS"},
        {"glyph": 1975, "appearance": "sling", "class": "WEAPON_CLASS"},
        {"glyph": 1976, "appearance": "crossbow", "class": "WEAPON_CLASS"},
    ],
    (")", "CLR_BLACK"): [
        {"glyph": 1909, "appearance": "crude arrow", "class": "WEAPON_CLASS"},
        {"glyph": 1918, "appearance": "crude spear", "class": "WEAPON_CLASS"},
        {"glyph": 1925, "appearance": "crude dagger", "class": "WEAPON_CLASS"},
        {"glyph": 1937, "appearance": "crude short sword", "class": "WEAPON_CLASS"},
        {"glyph": 1947, "appearance": "runed broadsword", "class": "WEAPON_CLASS"},
        {"glyph": 1973, "appearance": "crude bow", "class": "WEAPON_CLASS"},
    ],
    (")", "CLR_GRAY"): [
        {"glyph": 1910, "appearance": "silver arrow", "class": "WEAPON_CLASS"},
        {"glyph": 1920, "appearance": "silver spear", "class": "WEAPON_CLASS"},
        {"glyph": 1926, "appearance": "silver dagger", "class": "WEAPON_CLASS"},
        {"glyph": 1940, "appearance": "silver saber", "class": "WEAPON_CLASS"},
    ],
    (")", "CLR_WHITE"): [
        {"glyph": 1931, "appearance": "worm tooth", "class": "WEAPON_CLASS"},
        {"glyph": 1932, "appearance": "crysknife", "class": "WEAPON_CLASS"},
    ],
    ("[", "CLR_BROWN"): [
        {"glyph": 1977, "appearance": "leather hat", "class": "ARMOR_CLASS"},
        {"glyph": 1980, "appearance": "fedora", "class": "ARMOR_CLASS"},
        {"glyph": 2016, "appearance": "studded leather armor", "class": "ARMOR_CLASS"},
        {"glyph": 2019, "appearance": "leather armor", "class": "ARMOR_CLASS"},
        {"glyph": 2026, "appearance": "hooded cloak", "class": "ARMOR_CLASS"},
        {"glyph": 2027, "appearance": "slippery cloak", "class": "ARMOR_CLASS"},
        {"glyph": 2030, "appearance": "leather cloak", "class": "ARMOR_CLASS"},
        {"glyph": 2031, "appearance": "tattered cape", "class": "ARMOR_CLASS"},
        {"glyph": 2034, "appearance": "piece of cloth", "class": "ARMOR_CLASS"},
        {"glyph": 2035, "appearance": "small shield", "class": "ARMOR_CLASS"},
        {"glyph": 2042, "appearance": "old gloves", "class": "ARMOR_CLASS"},
        {"glyph": 2043, "appearance": "padded gloves", "class": "ARMOR_CLASS"},
        {"glyph": 2044, "appearance": "riding gloves", "class": "ARMOR_CLASS"},
        {"glyph": 2045, "appearance": "fencing gloves", "class": "ARMOR_CLASS"},
        {"glyph": 2046, "appearance": "walking shoes", "class": "ARMOR_CLASS"},
        {"glyph": 2048, "appearance": "jackboots", "class": "ARMOR_CLASS"},
        {"glyph": 2049, "appearance": "combat boots", "class": "ARMOR_CLASS"},
        {"glyph": 2050, "appearance": "jungle boots", "class": "ARMOR_CLASS"},
        {"glyph": 2051, "appearance": "hiking boots", "class": "ARMOR_CLASS"},
        {"glyph": 2052, "appearance": "mud boots", "class": "ARMOR_CLASS"},
        {"glyph": 2053, "appearance": "buckled boots", "class": "ARMOR_CLASS"},
        {"glyph": 2054, "appearance": "riding boots", "class": "ARMOR_CLASS"},
        {"glyph": 2055, "appearance": "snow boots", "class": "ARMOR_CLASS"},
    ],
    ("[", "CLR_BLACK"): [
        {"glyph": 1978, "appearance": "iron skull cap", "class": "ARMOR_CLASS"},
        {"glyph": 1983, "appearance": "dented pot", "class": "ARMOR_CLASS"},
        {
            "glyph": 1993,
            "appearance": "black dragon scale mail",
            "class": "ARMOR_CLASS",
        },
        {"glyph": 2002, "appearance": "black dragon scales", "class": "ARMOR_CLASS"},
        {"glyph": 2014, "appearance": "crude chain mail", "class": "ARMOR_CLASS"},
        {"glyph": 2018, "appearance": "crude ring mail", "class": "ARMOR_CLASS"},
        {"glyph": 2020, "appearance": "leather jacket", "class": "ARMOR_CLASS"},
        {"glyph": 2024, "appearance": "faded pall", "class": "ARMOR_CLASS"},
        {"glyph": 2025, "appearance": "coarse mantelet", "class": "ARMOR_CLASS"},
    ],
    ("[", "CLR_CYAN"): [
        {"glyph": 1979, "appearance": "hard hat", "class": "ARMOR_CLASS"},
        {"glyph": 1984, "appearance": "plumed helmet", "class": "ARMOR_CLASS"},
        {"glyph": 1986, "appearance": "crested helmet", "class": "ARMOR_CLASS"},
        {"glyph": 1987, "appearance": "visored helmet", "class": "ARMOR_CLASS"},
        {"glyph": 2006, "appearance": "plate mail", "class": "ARMOR_CLASS"},
        {"glyph": 2009, "appearance": "splint mail", "class": "ARMOR_CLASS"},
        {"glyph": 2010, "appearance": "banded mail", "class": "ARMOR_CLASS"},
        {"glyph": 2013, "appearance": "chain mail", "class": "ARMOR_CLASS"},
        {"glyph": 2015, "appearance": "scale mail", "class": "ARMOR_CLASS"},
        {"glyph": 2017, "appearance": "ring mail", "class": "ARMOR_CLASS"},
        {"glyph": 2037, "appearance": "white-handed shield", "class": "ARMOR_CLASS"},
        {"glyph": 2039, "appearance": "large shield", "class": "ARMOR_CLASS"},
        {"glyph": 2040, "appearance": "large round shield", "class": "ARMOR_CLASS"},
        {"glyph": 2047, "appearance": "hard shoes", "class": "ARMOR_CLASS"},
    ],
    ("[", "CLR_BLUE"): [
        {"glyph": 1981, "appearance": "conical hat", "class": "ARMOR_CLASS"},
        {"glyph": 1982, "appearance": "conical hat", "class": "ARMOR_CLASS"},
        {"glyph": 1994, "appearance": "blue dragon scale mail", "class": "ARMOR_CLASS"},
        {"glyph": 2003, "appearance": "blue dragon scales", "class": "ARMOR_CLASS"},
    ],
    ("[", "CLR_GREEN"): [
        {"glyph": 1985, "appearance": "etched helmet", "class": "ARMOR_CLASS"},
        {
            "glyph": 1995,
            "appearance": "green dragon scale mail",
            "class": "ARMOR_CLASS",
        },
        {"glyph": 2004, "appearance": "green dragon scales", "class": "ARMOR_CLASS"},
        {"glyph": 2036, "appearance": "blue and green shield", "class": "ARMOR_CLASS"},
    ],
    ("[", "CLR_GRAY"): [
        {"glyph": 1988, "appearance": "gray dragon scale mail", "class": "ARMOR_CLASS"},
        {"glyph": 1997, "appearance": "gray dragon scales", "class": "ARMOR_CLASS"},
        {"glyph": 2011, "appearance": "dwarvish mithril-coat", "class": "ARMOR_CLASS"},
        {"glyph": 2012, "appearance": "elven mithril-coat", "class": "ARMOR_CLASS"},
        {"glyph": 2023, "appearance": "mummy wrapping", "class": "ARMOR_CLASS"},
        {"glyph": 2041, "appearance": "polished silver shield", "class": "ARMOR_CLASS"},
    ],
    ("[", "CLR_BRIGHT_CYAN"): [
        {
            "glyph": 1989,
            "appearance": "silver dragon scale mail",
            "class": "ARMOR_CLASS",
        },
        {"glyph": 1998, "appearance": "silver dragon scales", "class": "ARMOR_CLASS"},
    ],
    ("[", "CLR_RED"): [
        {"glyph": 1990, "appearance": "red dragon scale mail", "class": "ARMOR_CLASS"},
        {"glyph": 1999, "appearance": "red dragon scales", "class": "ARMOR_CLASS"},
        {"glyph": 2028, "appearance": "robe", "class": "ARMOR_CLASS"},
        {"glyph": 2038, "appearance": "red-eyed shield", "class": "ARMOR_CLASS"},
    ],
    ("[", "CLR_WHITE"): [
        {
            "glyph": 1991,
            "appearance": "white dragon scale mail",
            "class": "ARMOR_CLASS",
        },
        {"glyph": 2000, "appearance": "white dragon scales", "class": "ARMOR_CLASS"},
        {"glyph": 2007, "appearance": "crystal plate mail", "class": "ARMOR_CLASS"},
        {"glyph": 2022, "appearance": "T-shirt", "class": "ARMOR_CLASS"},
        {"glyph": 2029, "appearance": "apron", "class": "ARMOR_CLASS"},
        {"glyph": 2033, "appearance": "ornamental cope", "class": "ARMOR_CLASS"},
    ],
    ("[", "CLR_ORANGE"): [
        {
            "glyph": 1992,
            "appearance": "orange dragon scale mail",
            "class": "ARMOR_CLASS",
        },
        {"glyph": 2001, "appearance": "orange dragon scales", "class": "ARMOR_CLASS"},
    ],
    ("[", "CLR_YELLOW"): [
        {
            "glyph": 1996,
            "appearance": "yellow dragon scale mail",
            "class": "ARMOR_CLASS",
        },
        {"glyph": 2005, "appearance": "yellow dragon scales", "class": "ARMOR_CLASS"},
        {"glyph": 2008, "appearance": "bronze plate mail", "class": "ARMOR_CLASS"},
    ],
    ("[", "CLR_MAGENTA"): [
        {"glyph": 2021, "appearance": "Hawaiian shirt", "class": "ARMOR_CLASS"}
    ],
    ("[", "CLR_BRIGHT_MAGENTA"): [
        {"glyph": 2032, "appearance": "opera cloak", "class": "ARMOR_CLASS"}
    ],
    ("=", "CLR_BROWN"): [
        {"glyph": 2056, "appearance": "wooden", "class": "RING_CLASS"},
        {"glyph": 2063, "appearance": "tiger eye", "class": "RING_CLASS"},
    ],
    ("=", "CLR_GRAY"): [
        {"glyph": 2057, "appearance": "granite", "class": "RING_CLASS"},
        {"glyph": 2058, "appearance": "opal", "class": "RING_CLASS"},
        {"glyph": 2062, "appearance": "moonstone", "class": "RING_CLASS"},
        {"glyph": 2077, "appearance": "silver", "class": "RING_CLASS"},
    ],
    ("=", "CLR_RED"): [
        {"glyph": 2059, "appearance": "clay", "class": "RING_CLASS"},
        {"glyph": 2066, "appearance": "agate", "class": "RING_CLASS"},
        {"glyph": 2069, "appearance": "ruby", "class": "RING_CLASS"},
    ],
    ("=", "CLR_ORANGE"): [
        {"glyph": 2060, "appearance": "coral", "class": "RING_CLASS"}
    ],
    ("=", "CLR_BLACK"): [
        {"glyph": 2061, "appearance": "black onyx", "class": "RING_CLASS"}
    ],
    ("=", "CLR_GREEN"): [{"glyph": 2064, "appearance": "jade", "class": "RING_CLASS"}],
    ("=", "CLR_YELLOW"): [
        {"glyph": 2065, "appearance": "bronze", "class": "RING_CLASS"},
        {"glyph": 2073, "appearance": "brass", "class": "RING_CLASS"},
        {"glyph": 2074, "appearance": "copper", "class": "RING_CLASS"},
        {"glyph": 2078, "appearance": "gold", "class": "RING_CLASS"},
    ],
    ("=", "CLR_CYAN"): [
        {"glyph": 2067, "appearance": "topaz", "class": "RING_CLASS"},
        {"glyph": 2072, "appearance": "iron", "class": "RING_CLASS"},
        {"glyph": 2075, "appearance": "twisted", "class": "RING_CLASS"},
        {"glyph": 2076, "appearance": "steel", "class": "RING_CLASS"},
        {"glyph": 2081, "appearance": "wire", "class": "RING_CLASS"},
        {"glyph": 2082, "appearance": "engagement", "class": "RING_CLASS"},
    ],
    ("=", "CLR_BLUE"): [
        {"glyph": 2068, "appearance": "sapphire", "class": "RING_CLASS"}
    ],
    ("=", "CLR_WHITE"): [
        {"glyph": 2070, "appearance": "diamond", "class": "RING_CLASS"},
        {"glyph": 2071, "appearance": "pearl", "class": "RING_CLASS"},
        {"glyph": 2079, "appearance": "ivory", "class": "RING_CLASS"},
    ],
    ("=", "CLR_BRIGHT_GREEN"): [
        {"glyph": 2080, "appearance": "emerald", "class": "RING_CLASS"}
    ],
    ("=", "CLR_BRIGHT_CYAN"): [
        {"glyph": 2083, "appearance": "shiny", "class": "RING_CLASS"}
    ],
    ('"', "CLR_CYAN"): [
        {"glyph": 2084, "appearance": "circular", "class": "AMULET_CLASS"},
        {"glyph": 2085, "appearance": "spherical", "class": "AMULET_CLASS"},
        {"glyph": 2086, "appearance": "oval", "class": "AMULET_CLASS"},
        {"glyph": 2087, "appearance": "triangular", "class": "AMULET_CLASS"},
        {"glyph": 2088, "appearance": "pyramidal", "class": "AMULET_CLASS"},
        {"glyph": 2089, "appearance": "square", "class": "AMULET_CLASS"},
        {"glyph": 2090, "appearance": "concave", "class": "AMULET_CLASS"},
        {"glyph": 2091, "appearance": "hexagonal", "class": "AMULET_CLASS"},
        {"glyph": 2092, "appearance": "octagonal", "class": "AMULET_CLASS"},
        {"glyph": 2093, "appearance": "Amulet of Yendor", "class": "AMULET_CLASS"},
        {"glyph": 2094, "appearance": "Amulet of Yendor", "class": "AMULET_CLASS"},
    ],
    ("(", "CLR_BROWN"): [
        {"glyph": 2095, "appearance": "large box", "class": "TOOL_CLASS"},
        {"glyph": 2096, "appearance": "chest", "class": "TOOL_CLASS"},
        {"glyph": 2098, "appearance": "bag", "class": "TOOL_CLASS"},
        {"glyph": 2099, "appearance": "bag", "class": "TOOL_CLASS"},
        {"glyph": 2100, "appearance": "bag", "class": "TOOL_CLASS"},
        {"glyph": 2101, "appearance": "bag", "class": "TOOL_CLASS"},
        {"glyph": 2116, "appearance": "saddle", "class": "TOOL_CLASS"},
        {"glyph": 2117, "appearance": "leash", "class": "TOOL_CLASS"},
        {"glyph": 2128, "appearance": "flute", "class": "TOOL_CLASS"},
        {"glyph": 2129, "appearance": "flute", "class": "TOOL_CLASS"},
        {"glyph": 2134, "appearance": "harp", "class": "TOOL_CLASS"},
        {"glyph": 2135, "appearance": "harp", "class": "TOOL_CLASS"},
        {"glyph": 2138, "appearance": "drum", "class": "TOOL_CLASS"},
        {"glyph": 2139, "appearance": "drum", "class": "TOOL_CLASS"},
    ],
    ("(", "CLR_WHITE"): [
        {"glyph": 2097, "appearance": "ice box", "class": "TOOL_CLASS"},
        {"glyph": 2104, "appearance": "credit card", "class": "TOOL_CLASS"},
        {"glyph": 2105, "appearance": "candle", "class": "TOOL_CLASS"},
        {"glyph": 2106, "appearance": "candle", "class": "TOOL_CLASS"},
        {"glyph": 2130, "appearance": "horn", "class": "TOOL_CLASS"},
        {"glyph": 2131, "appearance": "horn", "class": "TOOL_CLASS"},
        {"glyph": 2132, "appearance": "horn", "class": "TOOL_CLASS"},
        {"glyph": 2133, "appearance": "horn", "class": "TOOL_CLASS"},
        {"glyph": 2142, "appearance": "unicorn horn", "class": "TOOL_CLASS"},
    ],
    ("(", "CLR_CYAN"): [
        {"glyph": 2102, "appearance": "key", "class": "TOOL_CLASS"},
        {"glyph": 2103, "appearance": "lock pick", "class": "TOOL_CLASS"},
        {"glyph": 2118, "appearance": "stethoscope", "class": "TOOL_CLASS"},
        {"glyph": 2119, "appearance": "tinning kit", "class": "TOOL_CLASS"},
        {"glyph": 2120, "appearance": "tin opener", "class": "TOOL_CLASS"},
        {"glyph": 2121, "appearance": "can of grease", "class": "TOOL_CLASS"},
        {"glyph": 2125, "appearance": "beartrap", "class": "TOOL_CLASS"},
        {"glyph": 2126, "appearance": "whistle", "class": "TOOL_CLASS"},
        {"glyph": 2127, "appearance": "whistle", "class": "TOOL_CLASS"},
        {"glyph": 2140, "appearance": "pick-axe", "class": "TOOL_CLASS"},
        {"glyph": 2141, "appearance": "iron hook", "class": "TOOL_CLASS"},
    ],
    ("(", "CLR_YELLOW"): [
        {"glyph": 2107, "appearance": "brass lantern", "class": "TOOL_CLASS"},
        {"glyph": 2108, "appearance": "lamp", "class": "TOOL_CLASS"},
        {"glyph": 2109, "appearance": "lamp", "class": "TOOL_CLASS"},
        {"glyph": 2136, "appearance": "bell", "class": "TOOL_CLASS"},
        {"glyph": 2137, "appearance": "bugle", "class": "TOOL_CLASS"},
        {"glyph": 2143, "appearance": "candelabrum", "class": "TOOL_CLASS"},
    ],
    ("(", "CLR_BLACK"): [
        {"glyph": 2110, "appearance": "expensive camera", "class": "TOOL_CLASS"},
        {"glyph": 2114, "appearance": "blindfold", "class": "TOOL_CLASS"},
    ],
    ("(", "CLR_GRAY"): [
        {"glyph": 2111, "appearance": "looking glass", "class": "TOOL_CLASS"},
        {"glyph": 2122, "appearance": "figurine", "class": "TOOL_CLASS"},
        {"glyph": 2144, "appearance": "silver bell", "class": "TOOL_CLASS"},
    ],
    ("(", "CLR_BRIGHT_CYAN"): [
        {"glyph": 2112, "appearance": "glass orb", "class": "TOOL_CLASS"},
        {"glyph": 2113, "appearance": "lenses", "class": "TOOL_CLASS"},
    ],
    ("(", "CLR_MAGENTA"): [
        {"glyph": 2115, "appearance": "towel", "class": "TOOL_CLASS"}
    ],
    ("(", "CLR_RED"): [
        {"glyph": 2123, "appearance": "magic marker", "class": "TOOL_CLASS"},
        {"glyph": 2124, "appearance": "land mine", "class": "TOOL_CLASS"},
    ],
    ("%", "CLR_BROWN"): [
        {"glyph": 2145, "appearance": "tripe ration", "class": "FOOD_CLASS"},
        {"glyph": 2146, "appearance": "corpse", "class": "FOOD_CLASS"},
        {"glyph": 2148, "appearance": "meatball", "class": "FOOD_CLASS"},
        {"glyph": 2149, "appearance": "meat stick", "class": "FOOD_CLASS"},
        {"glyph": 2150, "appearance": "huge chunk of meat", "class": "FOOD_CLASS"},
        {"glyph": 2151, "appearance": "meat ring", "class": "FOOD_CLASS"},
        {"glyph": 2153, "appearance": "glob of brown pudding", "class": "FOOD_CLASS"},
        {"glyph": 2166, "appearance": "slime mold", "class": "FOOD_CLASS"},
        {"glyph": 2169, "appearance": "candy bar", "class": "FOOD_CLASS"},
        {"glyph": 2173, "appearance": "cram ration", "class": "FOOD_CLASS"},
        {"glyph": 2174, "appearance": "food ration", "class": "FOOD_CLASS"},
        {"glyph": 2175, "appearance": "K-ration", "class": "FOOD_CLASS"},
        {"glyph": 2176, "appearance": "C-ration", "class": "FOOD_CLASS"},
    ],
    ("%", "CLR_WHITE"): [
        {"glyph": 2147, "appearance": "egg", "class": "FOOD_CLASS"},
        {"glyph": 2165, "appearance": "clove of garlic", "class": "FOOD_CLASS"},
        {"glyph": 2168, "appearance": "cream pie", "class": "FOOD_CLASS"},
        {"glyph": 2172, "appearance": "lembas wafer", "class": "FOOD_CLASS"},
    ],
    ("%", "CLR_GRAY"): [
        {"glyph": 2152, "appearance": "glob of gray ooze", "class": "FOOD_CLASS"}
    ],
    ("%", "CLR_GREEN"): [
        {"glyph": 2154, "appearance": "glob of green slime", "class": "FOOD_CLASS"},
        {"glyph": 2156, "appearance": "kelp frond", "class": "FOOD_CLASS"},
        {"glyph": 2157, "appearance": "eucalyptus leaf", "class": "FOOD_CLASS"},
        {"glyph": 2164, "appearance": "sprig of wolfsbane", "class": "FOOD_CLASS"},
    ],
    ("%", "CLR_BLACK"): [
        {"glyph": 2155, "appearance": "glob of black pudding", "class": "FOOD_CLASS"}
    ],
    ("%", "CLR_RED"): [{"glyph": 2158, "appearance": "apple", "class": "FOOD_CLASS"}],
    ("%", "CLR_ORANGE"): [
        {"glyph": 2159, "appearance": "orange", "class": "FOOD_CLASS"},
        {"glyph": 2163, "appearance": "carrot", "class": "FOOD_CLASS"},
    ],
    ("%", "CLR_BRIGHT_GREEN"): [
        {"glyph": 2160, "appearance": "pear", "class": "FOOD_CLASS"},
        {"glyph": 2161, "appearance": "melon", "class": "FOOD_CLASS"},
    ],
    ("%", "CLR_YELLOW"): [
        {"glyph": 2162, "appearance": "banana", "class": "FOOD_CLASS"},
        {"glyph": 2167, "appearance": "lump of royal jelly", "class": "FOOD_CLASS"},
        {"glyph": 2170, "appearance": "fortune cookie", "class": "FOOD_CLASS"},
        {"glyph": 2171, "appearance": "pancake", "class": "FOOD_CLASS"},
    ],
    ("%", "CLR_CYAN"): [{"glyph": 2177, "appearance": "tin", "class": "FOOD_CLASS"}],
    ("!", "CLR_RED"): [
        {"glyph": 2178, "appearance": "ruby", "class": "POTION_CLASS"},
        {"glyph": 2189, "appearance": "puce", "class": "POTION_CLASS"},
    ],
    ("!", "CLR_BRIGHT_MAGENTA"): [
        {"glyph": 2179, "appearance": "pink", "class": "POTION_CLASS"}
    ],
    ("!", "CLR_ORANGE"): [
        {"glyph": 2180, "appearance": "orange", "class": "POTION_CLASS"}
    ],
    ("!", "CLR_YELLOW"): [
        {"glyph": 2181, "appearance": "yellow", "class": "POTION_CLASS"},
        {"glyph": 2197, "appearance": "golden", "class": "POTION_CLASS"},
    ],
    ("!", "CLR_BRIGHT_GREEN"): [
        {"glyph": 2182, "appearance": "emerald", "class": "POTION_CLASS"}
    ],
    ("!", "CLR_GREEN"): [
        {"glyph": 2183, "appearance": "dark green", "class": "POTION_CLASS"}
    ],
    ("!", "CLR_CYAN"): [
        {"glyph": 2184, "appearance": "cyan", "class": "POTION_CLASS"},
        {"glyph": 2185, "appearance": "sky blue", "class": "POTION_CLASS"},
        {"glyph": 2199, "appearance": "fizzy", "class": "POTION_CLASS"},
        {"glyph": 2203, "appearance": "clear", "class": "POTION_CLASS"},
    ],
    ("!", "CLR_BRIGHT_BLUE"): [
        {"glyph": 2186, "appearance": "brilliant blue", "class": "POTION_CLASS"}
    ],
    ("!", "CLR_MAGENTA"): [
        {"glyph": 2187, "appearance": "magenta", "class": "POTION_CLASS"},
        {"glyph": 2188, "appearance": "purple-red", "class": "POTION_CLASS"},
    ],
    ("!", "CLR_WHITE"): [
        {"glyph": 2190, "appearance": "milky", "class": "POTION_CLASS"},
        {"glyph": 2192, "appearance": "bubbly", "class": "POTION_CLASS"},
        {"glyph": 2194, "appearance": "cloudy", "class": "POTION_CLASS"},
        {"glyph": 2201, "appearance": "white", "class": "POTION_CLASS"},
    ],
    ("!", "CLR_BROWN"): [
        {"glyph": 2191, "appearance": "swirly", "class": "POTION_CLASS"},
        {"glyph": 2198, "appearance": "brown", "class": "POTION_CLASS"},
        {"glyph": 2202, "appearance": "murky", "class": "POTION_CLASS"},
    ],
    ("!", "CLR_GRAY"): [
        {"glyph": 2193, "appearance": "smoky", "class": "POTION_CLASS"},
        {"glyph": 2195, "appearance": "effervescent", "class": "POTION_CLASS"},
    ],
    ("!", "CLR_BLACK"): [
        {"glyph": 2196, "appearance": "black", "class": "POTION_CLASS"},
        {"glyph": 2200, "appearance": "dark", "class": "POTION_CLASS"},
    ],
    ("?", "CLR_WHITE"): [
        {"glyph": 2204, "appearance": "ZELGO MER", "class": "SCROLL_CLASS"},
        {"glyph": 2205, "appearance": "JUYED AWK YACC", "class": "SCROLL_CLASS"},
        {"glyph": 2206, "appearance": "NR 9", "class": "SCROLL_CLASS"},
        {"glyph": 2207, "appearance": "XIXAXA XOXAXA XUXAXA", "class": "SCROLL_CLASS"},
        {"glyph": 2208, "appearance": "PRATYAVAYAH", "class": "SCROLL_CLASS"},
        {"glyph": 2209, "appearance": "DAIYEN FOOELS", "class": "SCROLL_CLASS"},
        {"glyph": 2210, "appearance": "LEP GEX VEN ZEA", "class": "SCROLL_CLASS"},
        {"glyph": 2211, "appearance": "PRIRUTSENIE", "class": "SCROLL_CLASS"},
        {"glyph": 2212, "appearance": "ELBIB YLOH", "class": "SCROLL_CLASS"},
        {"glyph": 2213, "appearance": "VERR YED HORRE", "class": "SCROLL_CLASS"},
        {"glyph": 2214, "appearance": "VENZAR BORGAVVE", "class": "SCROLL_CLASS"},
        {"glyph": 2215, "appearance": "THARR", "class": "SCROLL_CLASS"},
        {"glyph": 2216, "appearance": "YUM YUM", "class": "SCROLL_CLASS"},
        {"glyph": 2217, "appearance": "KERNOD WEL", "class": "SCROLL_CLASS"},
        {"glyph": 2218, "appearance": "ELAM EBOW", "class": "SCROLL_CLASS"},
        {"glyph": 2219, "appearance": "DUAM XNAHT", "class": "SCROLL_CLASS"},
        {"glyph": 2220, "appearance": "ANDOVA BEGARIN", "class": "SCROLL_CLASS"},
        {"glyph": 2221, "appearance": "KIRJE", "class": "SCROLL_CLASS"},
        {"glyph": 2222, "appearance": "VE FORBRYDERNE", "class": "SCROLL_CLASS"},
        {"glyph": 2223, "appearance": "HACKEM MUCHE", "class": "SCROLL_CLASS"},
        {"glyph": 2224, "appearance": "VELOX NEB", "class": "SCROLL_CLASS"},
        {"glyph": 2225, "appearance": "FOOBIE BLETCH", "class": "SCROLL_CLASS"},
        {"glyph": 2226, "appearance": "TEMOV", "class": "SCROLL_CLASS"},
        {"glyph": 2227, "appearance": "GARVEN DEH", "class": "SCROLL_CLASS"},
        {"glyph": 2228, "appearance": "READ ME", "class": "SCROLL_CLASS"},
        {"glyph": 2229, "appearance": "ETAOIN SHRDLU", "class": "SCROLL_CLASS"},
        {"glyph": 2230, "appearance": "LOREM IPSUM", "class": "SCROLL_CLASS"},
        {"glyph": 2231, "appearance": "FNORD", "class": "SCROLL_CLASS"},
        {"glyph": 2232, "appearance": "KO BATE", "class": "SCROLL_CLASS"},
        {"glyph": 2233, "appearance": "ABRA KA DABRA", "class": "SCROLL_CLASS"},
        {"glyph": 2234, "appearance": "ASHPD SODALG", "class": "SCROLL_CLASS"},
        {"glyph": 2235, "appearance": "ZLORFIK", "class": "SCROLL_CLASS"},
        {"glyph": 2236, "appearance": "GNIK SISI VLE", "class": "SCROLL_CLASS"},
        {"glyph": 2237, "appearance": "HAPAX LEGOMENON", "class": "SCROLL_CLASS"},
        {"glyph": 2238, "appearance": "EIRIS SAZUN IDISI", "class": "SCROLL_CLASS"},
        {"glyph": 2239, "appearance": "PHOL ENDE WODAN", "class": "SCROLL_CLASS"},
        {"glyph": 2240, "appearance": "GHOTI", "class": "SCROLL_CLASS"},
        {"glyph": 2241, "appearance": "MAPIRO MAHAMA DIROMAT", "class": "SCROLL_CLASS"},
        {"glyph": 2242, "appearance": "VAS CORP BET MANI", "class": "SCROLL_CLASS"},
        {"glyph": 2243, "appearance": "XOR OTA", "class": "SCROLL_CLASS"},
        {"glyph": 2244, "appearance": "STRC PRST SKRZ KRK", "class": "SCROLL_CLASS"},
        {"glyph": 2245, "appearance": "unlabeled", "class": "SCROLL_CLASS"},
    ],
    ("+", "CLR_BROWN"): [
        {"glyph": 2246, "appearance": "parchment", "class": "SPBOOK_CLASS"},
        {"glyph": 2247, "appearance": "vellum", "class": "SPBOOK_CLASS"},
        {"glyph": 2252, "appearance": "cloth", "class": "SPBOOK_CLASS"},
        {"glyph": 2253, "appearance": "leathery", "class": "SPBOOK_CLASS"},
        {"glyph": 2270, "appearance": "tan", "class": "SPBOOK_CLASS"},
        {"glyph": 2272, "appearance": "light brown", "class": "SPBOOK_CLASS"},
        {"glyph": 2273, "appearance": "dark brown", "class": "SPBOOK_CLASS"},
    ],
    ("+", "CLR_WHITE"): [
        {"glyph": 2248, "appearance": "ragged", "class": "SPBOOK_CLASS"},
        {"glyph": 2249, "appearance": "dog eared", "class": "SPBOOK_CLASS"},
        {"glyph": 2250, "appearance": "mottled", "class": "SPBOOK_CLASS"},
        {"glyph": 2251, "appearance": "stained", "class": "SPBOOK_CLASS"},
        {"glyph": 2254, "appearance": "white", "class": "SPBOOK_CLASS"},
        {"glyph": 2275, "appearance": "wrinkled", "class": "SPBOOK_CLASS"},
        {"glyph": 2276, "appearance": "dusty", "class": "SPBOOK_CLASS"},
        {"glyph": 2281, "appearance": "glittering", "class": "SPBOOK_CLASS"},
        {"glyph": 2282, "appearance": "shining", "class": "SPBOOK_CLASS"},
        {"glyph": 2283, "appearance": "dull", "class": "SPBOOK_CLASS"},
        {"glyph": 2284, "appearance": "thin", "class": "SPBOOK_CLASS"},
        {"glyph": 2285, "appearance": "thick", "class": "SPBOOK_CLASS"},
        {"glyph": 2286, "appearance": "plain", "class": "SPBOOK_CLASS"},
        {"glyph": 2288, "appearance": "papyrus", "class": "SPBOOK_CLASS"},
    ],
    ("+", "CLR_BRIGHT_MAGENTA"): [
        {"glyph": 2255, "appearance": "pink", "class": "SPBOOK_CLASS"}
    ],
    ("+", "CLR_RED"): [{"glyph": 2256, "appearance": "red", "class": "SPBOOK_CLASS"}],
    ("+", "CLR_ORANGE"): [
        {"glyph": 2257, "appearance": "orange", "class": "SPBOOK_CLASS"}
    ],
    ("+", "CLR_YELLOW"): [
        {"glyph": 2258, "appearance": "yellow", "class": "SPBOOK_CLASS"},
        {"glyph": 2277, "appearance": "bronze", "class": "SPBOOK_CLASS"},
        {"glyph": 2278, "appearance": "copper", "class": "SPBOOK_CLASS"},
        {"glyph": 2280, "appearance": "gold", "class": "SPBOOK_CLASS"},
    ],
    ("+", "CLR_MAGENTA"): [
        {"glyph": 2259, "appearance": "velvet", "class": "SPBOOK_CLASS"},
        {"glyph": 2267, "appearance": "magenta", "class": "SPBOOK_CLASS"},
        {"glyph": 2268, "appearance": "purple", "class": "SPBOOK_CLASS"},
        {"glyph": 2269, "appearance": "violet", "class": "SPBOOK_CLASS"},
    ],
    ("+", "CLR_BRIGHT_GREEN"): [
        {"glyph": 2260, "appearance": "light green", "class": "SPBOOK_CLASS"}
    ],
    ("+", "CLR_GREEN"): [
        {"glyph": 2261, "appearance": "dark green", "class": "SPBOOK_CLASS"},
        {"glyph": 2271, "appearance": "plaid", "class": "SPBOOK_CLASS"},
    ],
    ("+", "CLR_BRIGHT_CYAN"): [
        {"glyph": 2262, "appearance": "turquoise", "class": "SPBOOK_CLASS"}
    ],
    ("+", "CLR_CYAN"): [{"glyph": 2263, "appearance": "cyan", "class": "SPBOOK_CLASS"}],
    ("+", "CLR_BRIGHT_BLUE"): [
        {"glyph": 2264, "appearance": "light blue", "class": "SPBOOK_CLASS"},
        {"glyph": 2287, "appearance": "paperback", "class": "SPBOOK_CLASS"},
    ],
    ("+", "CLR_BLUE"): [
        {"glyph": 2265, "appearance": "dark blue", "class": "SPBOOK_CLASS"},
        {"glyph": 2266, "appearance": "indigo", "class": "SPBOOK_CLASS"},
    ],
    ("+", "CLR_GRAY"): [
        {"glyph": 2274, "appearance": "gray", "class": "SPBOOK_CLASS"},
        {"glyph": 2279, "appearance": "silver", "class": "SPBOOK_CLASS"},
    ],
    ("/", "CLR_BRIGHT_CYAN"): [
        {"glyph": 2289, "appearance": "glass", "class": "WAND_CLASS"},
        {"glyph": 2291, "appearance": "crystal", "class": "WAND_CLASS"},
        {"glyph": 2302, "appearance": "iridium", "class": "WAND_CLASS"},
    ],
    ("/", "CLR_BROWN"): [
        {"glyph": 2290, "appearance": "balsa", "class": "WAND_CLASS"},
        {"glyph": 2292, "appearance": "maple", "class": "WAND_CLASS"},
        {"glyph": 2293, "appearance": "pine", "class": "WAND_CLASS"},
        {"glyph": 2294, "appearance": "oak", "class": "WAND_CLASS"},
        {"glyph": 2295, "appearance": "ebony", "class": "WAND_CLASS"},
        {"glyph": 2313, "appearance": "forked", "class": "WAND_CLASS"},
    ],
    ("/", "CLR_GRAY"): [
        {"glyph": 2296, "appearance": "marble", "class": "WAND_CLASS"},
        {"glyph": 2300, "appearance": "silver", "class": "WAND_CLASS"},
        {"glyph": 2315, "appearance": "jeweled", "class": "WAND_CLASS"},
    ],
    ("/", "CLR_CYAN"): [
        {"glyph": 2297, "appearance": "tin", "class": "WAND_CLASS"},
        {"glyph": 2303, "appearance": "zinc", "class": "WAND_CLASS"},
        {"glyph": 2304, "appearance": "aluminum", "class": "WAND_CLASS"},
        {"glyph": 2305, "appearance": "uranium", "class": "WAND_CLASS"},
        {"glyph": 2306, "appearance": "iron", "class": "WAND_CLASS"},
        {"glyph": 2307, "appearance": "steel", "class": "WAND_CLASS"},
        {"glyph": 2308, "appearance": "hexagonal", "class": "WAND_CLASS"},
        {"glyph": 2309, "appearance": "short", "class": "WAND_CLASS"},
        {"glyph": 2310, "appearance": "runed", "class": "WAND_CLASS"},
        {"glyph": 2311, "appearance": "long", "class": "WAND_CLASS"},
        {"glyph": 2312, "appearance": "curved", "class": "WAND_CLASS"},
        {"glyph": 2314, "appearance": "spiked", "class": "WAND_CLASS"},
    ],
    ("/", "CLR_YELLOW"): [
        {"glyph": 2298, "appearance": "brass", "class": "WAND_CLASS"},
        {"glyph": 2299, "appearance": "copper", "class": "WAND_CLASS"},
    ],
    ("/", "CLR_WHITE"): [
        {"glyph": 2301, "appearance": "platinum", "class": "WAND_CLASS"}
    ],
    ("$", "CLR_YELLOW"): [
        {"glyph": 2316, "appearance": "gold piece", "class": "COIN_CLASS"}
    ],
    ("*", "CLR_WHITE"): [
        {"glyph": 2317, "appearance": "white", "class": "GEM_CLASS"},
        {"glyph": 2318, "appearance": "white", "class": "GEM_CLASS"},
        {"glyph": 2330, "appearance": "white", "class": "GEM_CLASS"},
        {"glyph": 2339, "appearance": "white", "class": "GEM_CLASS"},
    ],
    ("*", "CLR_RED"): [
        {"glyph": 2319, "appearance": "red", "class": "GEM_CLASS"},
        {"glyph": 2332, "appearance": "red", "class": "GEM_CLASS"},
        {"glyph": 2334, "appearance": "red", "class": "GEM_CLASS"},
        {"glyph": 2341, "appearance": "red", "class": "GEM_CLASS"},
    ],
    ("*", "CLR_ORANGE"): [
        {"glyph": 2320, "appearance": "orange", "class": "GEM_CLASS"},
        {"glyph": 2337, "appearance": "orange", "class": "GEM_CLASS"},
        {"glyph": 2343, "appearance": "orange", "class": "GEM_CLASS"},
    ],
    ("*", "CLR_BLUE"): [
        {"glyph": 2321, "appearance": "blue", "class": "GEM_CLASS"},
        {"glyph": 2340, "appearance": "blue", "class": "GEM_CLASS"},
    ],
    ("*", "CLR_BLACK"): [
        {"glyph": 2322, "appearance": "black", "class": "GEM_CLASS"},
        {"glyph": 2329, "appearance": "black", "class": "GEM_CLASS"},
        {"glyph": 2336, "appearance": "black", "class": "GEM_CLASS"},
        {"glyph": 2345, "appearance": "black", "class": "GEM_CLASS"},
    ],
    ("*", "CLR_GREEN"): [
        {"glyph": 2323, "appearance": "green", "class": "GEM_CLASS"},
        {"glyph": 2324, "appearance": "green", "class": "GEM_CLASS"},
        {"glyph": 2326, "appearance": "green", "class": "GEM_CLASS"},
        {"glyph": 2338, "appearance": "green", "class": "GEM_CLASS"},
        {"glyph": 2346, "appearance": "green", "class": "GEM_CLASS"},
    ],
    ("*", "CLR_YELLOW"): [
        {"glyph": 2325, "appearance": "yellow", "class": "GEM_CLASS"},
        {"glyph": 2331, "appearance": "yellow", "class": "GEM_CLASS"},
        {"glyph": 2344, "appearance": "yellow", "class": "GEM_CLASS"},
    ],
    ("*", "CLR_BROWN"): [
        {"glyph": 2327, "appearance": "yellowish brown", "class": "GEM_CLASS"},
        {"glyph": 2328, "appearance": "yellowish brown", "class": "GEM_CLASS"},
        {"glyph": 2342, "appearance": "yellowish brown", "class": "GEM_CLASS"},
    ],
    ("*", "CLR_MAGENTA"): [
        {"glyph": 2333, "appearance": "violet", "class": "GEM_CLASS"},
        {"glyph": 2335, "appearance": "violet", "class": "GEM_CLASS"},
        {"glyph": 2347, "appearance": "violet", "class": "GEM_CLASS"},
    ],
    ("*", "CLR_GRAY"): [
        {"glyph": 2348, "appearance": "gray", "class": "GEM_CLASS"},
        {"glyph": 2349, "appearance": "gray", "class": "GEM_CLASS"},
        {"glyph": 2350, "appearance": "gray", "class": "GEM_CLASS"},
        {"glyph": 2351, "appearance": "gray", "class": "GEM_CLASS"},
        {"glyph": 2352, "appearance": "rock", "class": "GEM_CLASS"},
    ],
    ("`", "CLR_GRAY"): [
        {"glyph": 2353, "appearance": "boulder", "class": "ROCK_CLASS"}
    ],
    ("`", "CLR_WHITE"): [
        {"glyph": 2354, "appearance": "statue", "class": "ROCK_CLASS"}
    ],
    ("0", "CLR_CYAN"): [
        {"glyph": 2355, "appearance": "heavy iron ball", "class": "BALL_CLASS"}
    ],
    ("_", "CLR_CYAN"): [
        {"glyph": 2356, "appearance": "iron chain", "class": "CHAIN_CLASS"}
    ],
    (".", "CLR_BROWN"): [
        {"glyph": 2357, "appearance": "splash of venom", "class": "VENOM_CLASS"},
        {"glyph": 2358, "appearance": "splash of venom", "class": "VENOM_CLASS"},
    ],
}

trap_types = {
    "1": ("ARROW_TRAP", "CLR_CYAN"),
    "2": ("DART_TRAP", "CLR_CYAN"),  # same as above
    "3": ("ROCKTRAP", "CLR_GRAY"),
    "4": ("SQKY_BOARD", "CLR_BROWN"),
    "5": ("BEAR_TRAP", "CLR_CYAN"),
    "6": ("LANDMINE", "CLR_RED"),  # "CLR_ORANGE
    "7": ("ROLLING_BOULDER_TRAP", "CLR_GRAY"),
    "8": ("SLP_GAS_TRAP", "CLR_BRIGHT_BLUE"),
    "9": ("RUST_TRAP", "CLR_BLUE"),
    "10": ("FIRE_TRAP", "CLR_RED"),
    "11": ("PIT", "CLR_BLACK"),
    "12": ("SPIKED_PIT", "CLR_BLACK"),
    "13": ("HOLE", "CLR_BROWN"),
    "14": ("TRAPDOOR", "CLR_BROWN"),
    "15": ("TELEP_TRAP", "CLR_MAGENTA"),
    "16": ("LEVEL_TELEP", "CLR_MAGENTA"),
    "17": ("MAGIC_PORTAL", "CLR_BRIGHT_MAGENTA"),
    "18": ("WEB", "CLR_GRAY"),
    "19": ("STATUE_TRAP", "CLR_GRAY"),
    "20": ("MAGIC_TRAP", "CLR_BRIGHT_BLUE"),
    "21": ("ANTI_MAGIC", "CLR_BRIGHT_BLUE"),
    "22": ("POLY_TRAP", "CLR_BRIGHT_GREEN"),
    "23": ("VIBRATING_SQUARE", "CLR_MAGENTA"),
}


MON_TO_GLYPH = {
    ("a", "CLR_BROWN"): [{"glyph": 0, "name": "giant ant"}],
    ("a", "CLR_YELLOW"): [{"glyph": 1, "name": "killer bee"}],
    ("a", "CLR_BLUE"): [{"glyph": 2, "name": "soldier ant"}],
    ("a", "CLR_RED"): [{"glyph": 3, "name": "fire ant"}],
    ("a", "CLR_BLACK"): [{"glyph": 4, "name": "giant beetle"}],
    ("a", "CLR_MAGENTA"): [{"glyph": 5, "name": "queen bee"}],
    ("b", "CLR_GREEN"): [{"glyph": 6, "name": "acid blob"}],
    ("b", "CLR_WHITE"): [{"glyph": 7, "name": "quivering blob"}],
    ("b", "CLR_CYAN"): [{"glyph": 8, "name": "gelatinous cube"}],
    ("c", "CLR_BROWN"): [{"glyph": 9, "name": "chickatrice"}],
    ("c", "CLR_YELLOW"): [{"glyph": 10, "name": "cockatrice"}],
    ("c", "CLR_RED"): [{"glyph": 11, "name": "pyrolisk"}],
    ("d", "CLR_BROWN"): [
        {"glyph": 12, "name": "jackal"},
        {"glyph": 14, "name": "coyote"},
        {"glyph": 15, "name": "werejackal"},
        {"glyph": 20, "name": "wolf"},
        {"glyph": 21, "name": "werewolf"},
        {"glyph": 23, "name": "warg"},
    ],
    ("d", "CLR_RED"): [
        {"glyph": 13, "name": "fox"},
        {"glyph": 25, "name": "hell hound pup"},
        {"glyph": 26, "name": "hell hound"},
    ],
    ("d", "CLR_WHITE"): [
        {"glyph": 16, "name": "little dog"},
        {"glyph": 18, "name": "dog"},
        {"glyph": 19, "name": "large dog"},
    ],
    ("d", "CLR_YELLOW"): [{"glyph": 17, "name": "dingo"}],
    ("d", "CLR_CYAN"): [
        {"glyph": 22, "name": "winter wolf cub"},
        {"glyph": 24, "name": "winter wolf"},
    ],
    ("e", "CLR_GRAY"): [{"glyph": 27, "name": "gas spore"}],
    ("e", "CLR_BLUE"): [{"glyph": 28, "name": "floating eye"}],
    ("e", "CLR_WHITE"): [{"glyph": 29, "name": "freezing sphere"}],
    ("e", "CLR_RED"): [{"glyph": 30, "name": "flaming sphere"}],
    ("e", "CLR_BRIGHT_BLUE"): [{"glyph": 31, "name": "shocking sphere"}],
    ("f", "CLR_WHITE"): [
        {"glyph": 32, "name": "kitten"},
        {"glyph": 33, "name": "housecat"},
        {"glyph": 37, "name": "large cat"},
    ],
    ("f", "CLR_BROWN"): [{"glyph": 34, "name": "jaguar"}],
    ("f", "CLR_CYAN"): [{"glyph": 35, "name": "lynx"}],
    ("f", "CLR_BLACK"): [{"glyph": 36, "name": "panther"}],
    ("f", "CLR_YELLOW"): [{"glyph": 38, "name": "tiger"}],
    ("g", "CLR_GREEN"): [{"glyph": 39, "name": "gremlin"}],
    ("g", "CLR_BROWN"): [{"glyph": 40, "name": "gargoyle"}],
    ("g", "CLR_MAGENTA"): [{"glyph": 41, "name": "winged gargoyle"}],
    ("h", "CLR_GREEN"): [{"glyph": 42, "name": "hobbit"}],
    ("h", "CLR_RED"): [{"glyph": 43, "name": "dwarf"}],
    ("h", "CLR_BROWN"): [{"glyph": 44, "name": "bugbear"}],
    ("h", "CLR_BLUE"): [{"glyph": 45, "name": "dwarf lord"}],
    ("h", "CLR_MAGENTA"): [
        {"glyph": 46, "name": "dwarf king"},
        {"glyph": 47, "name": "mind flayer"},
        {"glyph": 48, "name": "master mind flayer"},
    ],
    ("i", "CLR_RED"): [{"glyph": 49, "name": "manes"}, {"glyph": 51, "name": "imp"}],
    ("i", "CLR_GREEN"): [{"glyph": 50, "name": "homunculus"}],
    ("i", "CLR_BROWN"): [{"glyph": 52, "name": "lemure"}],
    ("i", "CLR_BLUE"): [{"glyph": 53, "name": "quasit"}],
    ("i", "CLR_CYAN"): [{"glyph": 54, "name": "tengu"}],
    ("j", "CLR_BLUE"): [{"glyph": 55, "name": "blue jelly"}],
    ("j", "CLR_GREEN"): [{"glyph": 56, "name": "spotted jelly"}],
    ("j", "CLR_BROWN"): [{"glyph": 57, "name": "ochre jelly"}],
    ("k", "CLR_BROWN"): [{"glyph": 58, "name": "kobold"}],
    ("k", "CLR_RED"): [{"glyph": 59, "name": "large kobold"}],
    ("k", "CLR_MAGENTA"): [{"glyph": 60, "name": "kobold lord"}],
    ("k", "CLR_BRIGHT_BLUE"): [{"glyph": 61, "name": "kobold shaman"}],
    ("l", "CLR_GREEN"): [{"glyph": 62, "name": "leprechaun"}],
    ("m", "CLR_BROWN"): [{"glyph": 63, "name": "small mimic"}],
    ("m", "CLR_RED"): [{"glyph": 64, "name": "large mimic"}],
    ("m", "CLR_MAGENTA"): [{"glyph": 65, "name": "giant mimic"}],
    ("n", "CLR_GREEN"): [{"glyph": 66, "name": "wood nymph"}],
    ("n", "CLR_BLUE"): [{"glyph": 67, "name": "water nymph"}],
    ("n", "CLR_BROWN"): [{"glyph": 68, "name": "mountain nymph"}],
    ("o", "CLR_GRAY"): [{"glyph": 69, "name": "goblin"}],
    ("o", "CLR_BROWN"): [{"glyph": 70, "name": "hobgoblin"}],
    ("o", "CLR_RED"): [{"glyph": 71, "name": "orc"}],
    ("o", "CLR_YELLOW"): [{"glyph": 72, "name": "hill orc"}],
    ("o", "CLR_BLUE"): [{"glyph": 73, "name": "Mordor orc"}],
    ("o", "CLR_BLACK"): [{"glyph": 74, "name": "Uruk-hai"}],
    ("o", "CLR_BRIGHT_BLUE"): [{"glyph": 75, "name": "orc shaman"}],
    ("o", "CLR_MAGENTA"): [{"glyph": 76, "name": "orc-captain"}],
    ("p", "CLR_GRAY"): [{"glyph": 77, "name": "rock piercer"}],
    ("p", "CLR_CYAN"): [{"glyph": 78, "name": "iron piercer"}],
    ("p", "CLR_WHITE"): [{"glyph": 79, "name": "glass piercer"}],
    ("q", "CLR_BROWN"): [{"glyph": 80, "name": "rothe"}],
    ("q", "CLR_GRAY"): [
        {"glyph": 81, "name": "mumak"},
        {"glyph": 84, "name": "titanothere"},
        {"glyph": 85, "name": "baluchitherium"},
    ],
    ("q", "CLR_RED"): [{"glyph": 82, "name": "leocrotta"}],
    ("q", "CLR_CYAN"): [{"glyph": 83, "name": "wumpus"}],
    ("q", "CLR_BLACK"): [{"glyph": 86, "name": "mastodon"}],
    ("r", "CLR_BROWN"): [
        {"glyph": 87, "name": "sewer rat"},
        {"glyph": 88, "name": "giant rat"},
        {"glyph": 89, "name": "rabid rat"},
        {"glyph": 90, "name": "wererat"},
        {"glyph": 92, "name": "woodchuck"},
    ],
    ("r", "CLR_GRAY"): [{"glyph": 91, "name": "rock mole"}],
    ("s", "CLR_GRAY"): [{"glyph": 93, "name": "cave spider"}],
    ("s", "CLR_YELLOW"): [{"glyph": 94, "name": "centipede"}],
    ("s", "CLR_MAGENTA"): [
        {"glyph": 95, "name": "giant spider"},
        {"glyph": 362, "name": "Scorpius"},
    ],
    ("s", "CLR_RED"): [{"glyph": 96, "name": "scorpion"}],
    ("t", "CLR_GRAY"): [{"glyph": 97, "name": "lurker above"}],
    ("t", "CLR_GREEN"): [{"glyph": 98, "name": "trapper"}],
    ("u", "CLR_BROWN"): [
        {"glyph": 99, "name": "pony"},
        {"glyph": 103, "name": "horse"},
        {"glyph": 104, "name": "warhorse"},
    ],
    ("u", "CLR_WHITE"): [{"glyph": 100, "name": "white unicorn"}],
    ("u", "CLR_GRAY"): [{"glyph": 101, "name": "gray unicorn"}],
    ("u", "CLR_BLACK"): [{"glyph": 102, "name": "black unicorn"}],
    ("v", "CLR_GRAY"): [{"glyph": 105, "name": "fog cloud"}],
    ("v", "CLR_BROWN"): [{"glyph": 106, "name": "dust vortex"}],
    ("v", "CLR_CYAN"): [{"glyph": 107, "name": "ice vortex"}],
    ("v", "CLR_BRIGHT_BLUE"): [{"glyph": 108, "name": "energy vortex"}],
    ("v", "CLR_BLUE"): [{"glyph": 109, "name": "steam vortex"}],
    ("v", "CLR_YELLOW"): [{"glyph": 110, "name": "fire vortex"}],
    ("w", "CLR_BROWN"): [
        {"glyph": 111, "name": "baby long worm"},
        {"glyph": 113, "name": "long worm"},
    ],
    ("w", "CLR_MAGENTA"): [
        {"glyph": 112, "name": "baby purple worm"},
        {"glyph": 114, "name": "purple worm"},
    ],
    ("x", "CLR_MAGENTA"): [{"glyph": 115, "name": "grid bug"}],
    ("x", "CLR_RED"): [{"glyph": 116, "name": "xan"}],
    ("y", "CLR_YELLOW"): [{"glyph": 117, "name": "yellow light"}],
    ("y", "CLR_BLACK"): [{"glyph": 118, "name": "black light"}],
    ("z", "CLR_BROWN"): [{"glyph": 119, "name": "zruty"}],
    ("A", "CLR_GREEN"): [{"glyph": 120, "name": "couatl"}],
    ("A", "CLR_YELLOW"): [
        {"glyph": 121, "name": "Aleax"},
        {"glyph": 123, "name": "ki-rin"},
    ],
    ("A", "CLR_WHITE"): [{"glyph": 122, "name": "Angel"}],
    ("A", "CLR_MAGENTA"): [{"glyph": 124, "name": "Archon"}],
    ("B", "CLR_BROWN"): [{"glyph": 125, "name": "bat"}],
    ("B", "CLR_RED"): [{"glyph": 126, "name": "giant bat"}],
    ("B", "CLR_BLACK"): [
        {"glyph": 127, "name": "raven"},
        {"glyph": 128, "name": "vampire bat"},
    ],
    ("C", "CLR_BROWN"): [{"glyph": 129, "name": "plains centaur"}],
    ("C", "CLR_GREEN"): [{"glyph": 130, "name": "forest centaur"}],
    ("C", "CLR_CYAN"): [{"glyph": 131, "name": "mountain centaur"}],
    ("D", "CLR_GRAY"): [
        {"glyph": 132, "name": "baby gray dragon"},
        {"glyph": 141, "name": "gray dragon"},
    ],
    ("D", "CLR_BRIGHT_CYAN"): [
        {"glyph": 133, "name": "baby silver dragon"},
        {"glyph": 142, "name": "silver dragon"},
    ],
    ("D", "CLR_RED"): [
        {"glyph": 134, "name": "baby red dragon"},
        {"glyph": 143, "name": "red dragon"},
        {"glyph": 359, "name": "Ixoth"},
    ],
    ("D", "CLR_WHITE"): [
        {"glyph": 135, "name": "baby white dragon"},
        {"glyph": 144, "name": "white dragon"},
    ],
    ("D", "CLR_ORANGE"): [
        {"glyph": 136, "name": "baby orange dragon"},
        {"glyph": 145, "name": "orange dragon"},
    ],
    ("D", "CLR_BLACK"): [
        {"glyph": 137, "name": "baby black dragon"},
        {"glyph": 146, "name": "black dragon"},
    ],
    ("D", "CLR_BLUE"): [
        {"glyph": 138, "name": "baby blue dragon"},
        {"glyph": 147, "name": "blue dragon"},
    ],
    ("D", "CLR_GREEN"): [
        {"glyph": 139, "name": "baby green dragon"},
        {"glyph": 148, "name": "green dragon"},
    ],
    ("D", "CLR_YELLOW"): [
        {"glyph": 140, "name": "baby yellow dragon"},
        {"glyph": 149, "name": "yellow dragon"},
    ],
    ("E", "CLR_WHITE"): [{"glyph": 150, "name": "stalker"}],
    ("E", "CLR_CYAN"): [{"glyph": 151, "name": "air elemental"}],
    ("E", "CLR_YELLOW"): [{"glyph": 152, "name": "fire elemental"}],
    ("E", "CLR_BROWN"): [{"glyph": 153, "name": "earth elemental"}],
    ("E", "CLR_BLUE"): [{"glyph": 154, "name": "water elemental"}],
    ("F", "CLR_BRIGHT_GREEN"): [{"glyph": 155, "name": "lichen"}],
    ("F", "CLR_BROWN"): [{"glyph": 156, "name": "brown mold"}],
    ("F", "CLR_YELLOW"): [{"glyph": 157, "name": "yellow mold"}],
    ("F", "CLR_GREEN"): [{"glyph": 158, "name": "green mold"}],
    ("F", "CLR_RED"): [{"glyph": 159, "name": "red mold"}],
    ("F", "CLR_MAGENTA"): [
        {"glyph": 160, "name": "shrieker"},
        {"glyph": 161, "name": "fungus"},
    ],
    ("G", "CLR_BROWN"): [{"glyph": 162, "name": "gnome"}],
    ("G", "CLR_BLUE"): [{"glyph": 163, "name": "gnome lord"}],
    ("G", "CLR_BRIGHT_BLUE"): [{"glyph": 164, "name": "gnomish wizard"}],
    ("G", "CLR_MAGENTA"): [{"glyph": 165, "name": "gnome king"}],
    ("H", "CLR_RED"): [{"glyph": 166, "name": "giant"}],
    ("H", "CLR_GRAY"): [
        {"glyph": 167, "name": "stone giant"},
        {"glyph": 358, "name": "Cyclops"},
    ],
    ("H", "CLR_CYAN"): [{"glyph": 168, "name": "hill giant"}],
    ("H", "CLR_YELLOW"): [{"glyph": 169, "name": "fire giant"}],
    ("H", "CLR_WHITE"): [{"glyph": 170, "name": "frost giant"}],
    ("H", "CLR_BROWN"): [
        {"glyph": 171, "name": "ettin"},
        {"glyph": 174, "name": "minotaur"},
    ],
    ("H", "CLR_BLUE"): [{"glyph": 172, "name": "storm giant"}],
    ("H", "CLR_MAGENTA"): [
        {"glyph": 173, "name": "titan"},
        {"glyph": 365, "name": "Lord Surtur"},
    ],
    ("I", "CLR_WHITE"): [{"glyph": -1, "name": " it"}],
    ("J", "CLR_ORANGE"): [{"glyph": 175, "name": "jabberwock"}],
    ("K", "CLR_BLUE"): [
        {"glyph": 176, "name": "Keystone Kop"},
        {"glyph": 177, "name": "Kop Sergeant"},
    ],
    ("K", "CLR_CYAN"): [{"glyph": 178, "name": "Kop Lieutenant"}],
    ("K", "CLR_MAGENTA"): [{"glyph": 179, "name": "Kop Kaptain"}],
    ("L", "CLR_BROWN"): [{"glyph": 180, "name": "lich"}],
    ("L", "CLR_RED"): [{"glyph": 181, "name": "demilich"}],
    ("L", "CLR_MAGENTA"): [
        {"glyph": 182, "name": "master lich"},
        {"glyph": 183, "name": "arch-lich"},
    ],
    ("M", "CLR_BROWN"): [{"glyph": 184, "name": "kobold mummy"}],
    ("M", "CLR_RED"): [
        {"glyph": 185, "name": "gnome mummy"},
        {"glyph": 187, "name": "dwarf mummy"},
    ],
    ("M", "CLR_GRAY"): [
        {"glyph": 186, "name": "orc mummy"},
        {"glyph": 189, "name": "human mummy"},
    ],
    ("M", "CLR_GREEN"): [{"glyph": 188, "name": "elf mummy"}],
    ("M", "CLR_BLUE"): [{"glyph": 190, "name": "ettin mummy"}],
    ("M", "CLR_CYAN"): [{"glyph": 191, "name": "giant mummy"}],
    ("N", "CLR_RED"): [
        {"glyph": 192, "name": "red naga hatchling"},
        {"glyph": 196, "name": "red naga"},
    ],
    ("N", "CLR_BLACK"): [
        {"glyph": 193, "name": "black naga hatchling"},
        {"glyph": 197, "name": "black naga"},
    ],
    ("N", "CLR_YELLOW"): [
        {"glyph": 194, "name": "golden naga hatchling"},
        {"glyph": 198, "name": "golden naga"},
    ],
    ("N", "CLR_GREEN"): [
        {"glyph": 195, "name": "guardian naga hatchling"},
        {"glyph": 199, "name": "guardian naga"},
    ],
    ("O", "CLR_BROWN"): [{"glyph": 200, "name": "ogre"}],
    ("O", "CLR_RED"): [{"glyph": 201, "name": "ogre lord"}],
    ("O", "CLR_MAGENTA"): [{"glyph": 202, "name": "ogre king"}],
    ("P", "CLR_GRAY"): [{"glyph": 203, "name": "gray ooze"}],
    ("P", "CLR_BROWN"): [{"glyph": 204, "name": "brown pudding"}],
    ("P", "CLR_GREEN"): [{"glyph": 205, "name": "green slime"}],
    ("P", "CLR_BLACK"): [{"glyph": 206, "name": "black pudding"}],
    ("Q", "CLR_CYAN"): [{"glyph": 207, "name": "quantum mechanic"}],
    ("R", "CLR_BROWN"): [{"glyph": 208, "name": "rust monster"}],
    ("R", "CLR_BLUE"): [{"glyph": 209, "name": "disenchanter"}],
    ("S", "CLR_GREEN"): [{"glyph": 210, "name": "garter snake"}],
    ("S", "CLR_BROWN"): [{"glyph": 211, "name": "snake"}],
    ("S", "CLR_RED"): [{"glyph": 212, "name": "water moccasin"}],
    ("S", "CLR_MAGENTA"): [{"glyph": 213, "name": "python"}],
    ("S", "CLR_BLUE"): [
        {"glyph": 214, "name": "pit viper"},
        {"glyph": 215, "name": "cobra"},
    ],
    ("T", "CLR_BROWN"): [{"glyph": 216, "name": "troll"}],
    ("T", "CLR_WHITE"): [{"glyph": 217, "name": "ice troll"}],
    ("T", "CLR_CYAN"): [{"glyph": 218, "name": "rock troll"}],
    ("T", "CLR_BLUE"): [{"glyph": 219, "name": "water troll"}],
    ("T", "CLR_MAGENTA"): [{"glyph": 220, "name": "Olog-hai"}],
    ("U", "CLR_BROWN"): [{"glyph": 221, "name": "umber hulk"}],
    ("V", "CLR_RED"): [{"glyph": 222, "name": "vampire"}],
    ("V", "CLR_BLUE"): [{"glyph": 223, "name": "vampire lord"}],
    ("V", "CLR_MAGENTA"): [{"glyph": 224, "name": "Vlad the Impaler"}],
    ("W", "CLR_GRAY"): [{"glyph": 225, "name": "barrow wight"}],
    ("W", "CLR_BLACK"): [{"glyph": 226, "name": "wraith"}],
    ("W", "CLR_MAGENTA"): [{"glyph": 227, "name": "Nazgul"}],
    ("X", "CLR_BROWN"): [{"glyph": 228, "name": "xorn"}],
    ("Y", "CLR_GRAY"): [
        {"glyph": 229, "name": "monkey"},
        {"glyph": 234, "name": "sasquatch"},
    ],
    ("Y", "CLR_BROWN"): [
        {"glyph": 230, "name": "ape"},
        {"glyph": 231, "name": "owlbear"},
    ],
    ("Y", "CLR_WHITE"): [{"glyph": 232, "name": "yeti"}],
    ("Y", "CLR_BLACK"): [{"glyph": 233, "name": "carnivorous ape"}],
    ("Z", "CLR_BROWN"): [
        {"glyph": 235, "name": "kobold zombie"},
        {"glyph": 236, "name": "gnome zombie"},
    ],
    ("Z", "CLR_GRAY"): [{"glyph": 237, "name": "orc zombie"}],
    ("Z", "CLR_RED"): [{"glyph": 238, "name": "dwarf zombie"}],
    ("Z", "CLR_GREEN"): [{"glyph": 239, "name": "elf zombie"}],
    ("Z", "CLR_WHITE"): [
        {"glyph": 240, "name": "human zombie"},
        {"glyph": 244, "name": "skeleton"},
    ],
    ("Z", "CLR_BLUE"): [{"glyph": 241, "name": "ettin zombie"}],
    ("Z", "CLR_BLACK"): [{"glyph": 242, "name": "ghoul"}],
    ("Z", "CLR_CYAN"): [{"glyph": 243, "name": "giant zombie"}],
    ("'", "CLR_YELLOW"): [
        {"glyph": 245, "name": "straw golem"},
        {"glyph": 248, "name": "gold golem"},
    ],
    ("'", "CLR_WHITE"): [{"glyph": 246, "name": "paper golem"}],
    ("'", "CLR_BROWN"): [
        {"glyph": 247, "name": "rope golem"},
        {"glyph": 249, "name": "leather golem"},
        {"glyph": 250, "name": "wood golem"},
        {"glyph": 252, "name": "clay golem"},
    ],
    ("'", "CLR_RED"): [{"glyph": 251, "name": "flesh golem"}],
    ("'", "CLR_GRAY"): [{"glyph": 253, "name": "stone golem"}],
    ("'", "CLR_CYAN"): [
        {"glyph": 254, "name": "glass golem"},
        {"glyph": 255, "name": "iron golem"},
    ],
    ("@", "CLR_WHITE"): [
        {"glyph": 256, "name": "human"},
        {"glyph": 260, "name": "elf"},
        {"glyph": 266, "name": "doppelganger"},
        {"glyph": 267, "name": "shopkeeper"},
        {"glyph": 269, "name": "prisoner"},
        {"glyph": 271, "name": "aligned priest"},
        {"glyph": 272, "name": "high priest"},
        {"glyph": 275, "name": "nurse"},
        {"glyph": 327, "name": "archeologist"},
        {"glyph": 328, "name": "barbarian"},
        {"glyph": 329, "name": "caveman"},
        {"glyph": 330, "name": "cavewoman"},
        {"glyph": 331, "name": "healer"},
        {"glyph": 332, "name": "knight"},
        {"glyph": 333, "name": "monk"},
        {"glyph": 334, "name": "priest"},
        {"glyph": 335, "name": "priestess"},
        {"glyph": 336, "name": "ranger"},
        {"glyph": 337, "name": "rogue"},
        {"glyph": 338, "name": "samurai"},
        {"glyph": 339, "name": "tourist"},
        {"glyph": 340, "name": "valkyrie"},
        {"glyph": 341, "name": "wizard"},
        {"glyph": 348, "name": "Arch Priest"},
        {"glyph": 352, "name": "Twoflower"},
        {"glyph": 367, "name": "student"},
        {"glyph": 368, "name": "chieftain"},
        {"glyph": 369, "name": "neanderthal"},
        {"glyph": 370, "name": "attendant"},
        {"glyph": 371, "name": "page"},
        {"glyph": 372, "name": "abbot"},
        {"glyph": 373, "name": "acolyte"},
        {"glyph": 374, "name": "hunter"},
        {"glyph": 375, "name": "thug"},
        {"glyph": 376, "name": "ninja"},
        {"glyph": 377, "name": "roshi"},
        {"glyph": 378, "name": "guide"},
        {"glyph": 379, "name": "warrior"},
        {"glyph": 380, "name": "apprentice"},
    ],
    ("@", "CLR_BROWN"): [{"glyph": 257, "name": "wererat"}],
    ("@", "CLR_RED"): [
        {"glyph": 258, "name": "werejackal"},
        {"glyph": 274, "name": "sergeant"},
    ],
    ("@", "CLR_ORANGE"): [{"glyph": 259, "name": "werewolf"}],
    ("@", "CLR_GREEN"): [
        {"glyph": 261, "name": "Woodland-elf"},
        {"glyph": 276, "name": "lieutenant"},
        {"glyph": 279, "name": "watch captain"},
        {"glyph": 354, "name": "Neferet the Green"},
    ],
    ("@", "CLR_BRIGHT_GREEN"): [
        {"glyph": 262, "name": "Green-elf"},
        {"glyph": 280, "name": "Medusa"},
    ],
    ("@", "CLR_GRAY"): [
        {"glyph": 263, "name": "Grey-elf"},
        {"glyph": 273, "name": "soldier"},
        {"glyph": 278, "name": "watchman"},
    ],
    ("@", "CLR_BRIGHT_BLUE"): [
        {"glyph": 264, "name": "elf-lord"},
        {"glyph": 270, "name": "Oracle"},
    ],
    ("@", "CLR_MAGENTA"): [
        {"glyph": 265, "name": "Elvenking"},
        {"glyph": 281, "name": "Wizard of Yendor"},
        {"glyph": 282, "name": "Croesus"},
        {"glyph": 342, "name": "Lord Carnarvon"},
        {"glyph": 343, "name": "Pelias"},
        {"glyph": 344, "name": "Shaman Karnov"},
        {"glyph": 345, "name": "Hippocrates"},
        {"glyph": 346, "name": "King Arthur"},
        {"glyph": 349, "name": "Orion"},
        {"glyph": 350, "name": "Master of Thieves"},
        {"glyph": 351, "name": "Lord Sato"},
        {"glyph": 353, "name": "Norn"},
        {"glyph": 356, "name": "Thoth Amon"},
        {"glyph": 360, "name": "Master Kaen"},
        {"glyph": 363, "name": "Master Assassin"},
        {"glyph": 364, "name": "Ashikaga Takauji"},
    ],
    ("@", "CLR_BLUE"): [
        {"glyph": 268, "name": "guard"},
        {"glyph": 277, "name": "captain"},
    ],
    ("", "CLR_GRAY"): [{"glyph": 283, "name": "ghost"}],
    ("", "CLR_BLACK"): [{"glyph": 284, "name": "shade"}],
    ("&", "CLR_BLUE"): [{"glyph": 285, "name": "water demon"}],
    ("&", "CLR_GRAY"): [
        {"glyph": 286, "name": "succubus"},
        {"glyph": 288, "name": "incubus"},
        {"glyph": 294, "name": "bone devil"},
        {"glyph": 298, "name": "sandestin"},
    ],
    ("&", "CLR_BROWN"): [{"glyph": 287, "name": "horned devil"}],
    ("&", "CLR_RED"): [
        {"glyph": 289, "name": "erinys"},
        {"glyph": 290, "name": "barbed devil"},
        {"glyph": 291, "name": "marilith"},
        {"glyph": 292, "name": "vrock"},
        {"glyph": 293, "name": "hezrou"},
        {"glyph": 296, "name": "nalfeshnee"},
        {"glyph": 297, "name": "pit fiend"},
        {"glyph": 299, "name": "balrog"},
        {"glyph": 355, "name": "Minion of Huhetotl"},
        {"glyph": 361, "name": "Nalzok"},
    ],
    ("&", "CLR_WHITE"): [{"glyph": 295, "name": "ice devil"}],
    ("&", "CLR_BRIGHT_GREEN"): [{"glyph": 300, "name": "Juiblex"}],
    ("&", "CLR_MAGENTA"): [
        {"glyph": 301, "name": "Yeenoghu"},
        {"glyph": 302, "name": "Orcus"},
        {"glyph": 303, "name": "Geryon"},
        {"glyph": 304, "name": "Dispater"},
        {"glyph": 305, "name": "Baalzebub"},
        {"glyph": 306, "name": "Asmodeus"},
        {"glyph": 307, "name": "Demogorgon"},
        {"glyph": 308, "name": "Death"},
        {"glyph": 309, "name": "Pestilence"},
        {"glyph": 310, "name": "Famine"},
    ],
    ("&", "CLR_YELLOW"): [{"glyph": 311, "name": "djinni"}],
    (";", "CLR_BLUE"): [{"glyph": 312, "name": "jellyfish"}],
    (";", "CLR_RED"): [
        {"glyph": 313, "name": "piranha"},
        {"glyph": 317, "name": "kraken"},
    ],
    (";", "CLR_GRAY"): [{"glyph": 314, "name": "shark"}],
    (";", "CLR_CYAN"): [{"glyph": 315, "name": "giant eel"}],
    (";", "CLR_BRIGHT_BLUE"): [{"glyph": 316, "name": "electric eel"}],
    (":", "CLR_YELLOW"): [{"glyph": 318, "name": "newt"}],
    (":", "CLR_GREEN"): [
        {"glyph": 319, "name": "gecko"},
        {"glyph": 322, "name": "lizard"},
    ],
    (":", "CLR_BROWN"): [
        {"glyph": 320, "name": "iguana"},
        {"glyph": 321, "name": "baby crocodile"},
        {"glyph": 323, "name": "chameleon"},
        {"glyph": 324, "name": "crocodile"},
    ],
    (":", "CLR_ORANGE"): [{"glyph": 325, "name": "salamander"}],
    ("~", "CLR_BROWN"): [{"glyph": 326, "name": "long worm tail"}],
    ("@", "CLR_BLACK"): [
        {"glyph": 347, "name": "Grand Master"},
        {"glyph": 366, "name": "Dark One"},
    ],
    ("D", "CLR_MAGENTA"): [{"glyph": 357, "name": "Chromatic Dragon"}],
}

TRAP_TO_GLYPH_DICT = {
    ("^", "CLR_CYAN"): [
        {"glyph": 2401, "appearance": "ARROW_TRAP"},
        {"glyph": 2402, "appearance": "DART_TRAP"},
        {"glyph": 2405, "appearance": "BEAR_TRAP"},
    ],
    ("^", "CLR_GRAY"): [
        {"glyph": 2403, "appearance": "ROCKTRAP"},
        {"glyph": 2407, "appearance": "ROLLING_BOULDER_TRAP"},
        {"glyph": 2418, "appearance": "WEB"},
        {"glyph": 2419, "appearance": "STATUE_TRAP"},
    ],
    ("^", "CLR_BROWN"): [
        {"glyph": 2404, "appearance": "SQKY_BOARD"},
        {"glyph": 2413, "appearance": "HOLE"},
        {"glyph": 2414, "appearance": "TRAPDOOR"},
    ],
    ("^", "CLR_RED"): [
        {"glyph": 2406, "appearance": "LANDMINE"},
        {"glyph": 2410, "appearance": "FIRE_TRAP"},
    ],
    ("^", "CLR_BRIGHT_BLUE"): [
        {"glyph": 2408, "appearance": "SLP_GAS_TRAP"},
        {"glyph": 2420, "appearance": "MAGIC_TRAP"},
        {"glyph": 2421, "appearance": "ANTI_MAGIC"},
    ],
    ("^", "CLR_BLUE"): [{"glyph": 2409, "appearance": "RUST_TRAP"}],
    ("^", "CLR_BLACK"): [
        {"glyph": 2411, "appearance": "PIT"},
        {"glyph": 2412, "appearance": "SPIKED_PIT"},
    ],
    ("^", "CLR_MAGENTA"): [
        {"glyph": 2415, "appearance": "TELEP_TRAP"},
        {"glyph": 2416, "appearance": "LEVEL_TELEP"},
        {"glyph": 2423, "appearance": "VIBRATING_SQUARE"},
    ],
    ("^", "CLR_BRIGHT_MAGENTA"): [{"glyph": 2417, "appearance": "MAGIC_PORTAL"}],
    ("^", "CLR_BRIGHT_GREEN"): [{"glyph": 2422, "appearance": "POLY_TRAP"}],
}


PETS_TO_GLYPH = {
    ("a", "PET_CLR_BROWN"): [{"glyph": 381, "name": "giant ant"}],
    ("a", "PET_CLR_YELLOW"): [{"glyph": 382, "name": "killer bee"}],
    ("a", "PET_CLR_BLUE"): [{"glyph": 383, "name": "soldier ant"}],
    ("a", "PET_CLR_RED"): [{"glyph": 384, "name": "fire ant"}],
    ("a", "PET_CLR_BLACK"): [{"glyph": 385, "name": "giant beetle"}],
    ("a", "PET_CLR_MAGENTA"): [{"glyph": 386, "name": "queen bee"}],
    ("b", "PET_CLR_GREEN"): [{"glyph": 387, "name": "acid blob"}],
    ("b", "PET_CLR_WHITE"): [{"glyph": 388, "name": "quivering blob"}],
    ("b", "PET_CLR_CYAN"): [{"glyph": 389, "name": "gelatinous cube"}],
    ("c", "PET_CLR_BROWN"): [{"glyph": 390, "name": "chickatrice"}],
    ("c", "PET_CLR_YELLOW"): [{"glyph": 391, "name": "cockatrice"}],
    ("c", "PET_CLR_RED"): [{"glyph": 392, "name": "pyrolisk"}],
    ("d", "PET_CLR_BROWN"): [
        {"glyph": 393, "name": "jackal"},
        {"glyph": 395, "name": "coyote"},
        {"glyph": 396, "name": "werejackal"},
        {"glyph": 401, "name": "wolf"},
        {"glyph": 402, "name": "werewolf"},
        {"glyph": 404, "name": "warg"},
    ],
    ("d", "PET_CLR_RED"): [
        {"glyph": 394, "name": "fox"},
        {"glyph": 406, "name": "hell hound pup"},
        {"glyph": 407, "name": "hell hound"},
    ],
    ("d", "PET_CLR_WHITE"): [
        {"glyph": 397, "name": "little dog"},
        {"glyph": 399, "name": "dog"},
        {"glyph": 400, "name": "large dog"},
    ],
    ("d", "PET_CLR_YELLOW"): [{"glyph": 398, "name": "dingo"}],
    ("d", "PET_CLR_CYAN"): [
        {"glyph": 403, "name": "winter wolf cub"},
        {"glyph": 405, "name": "winter wolf"},
    ],
    ("e", "PET_CLR_GRAY"): [{"glyph": 408, "name": "gas spore"}],
    ("e", "PET_CLR_BLUE"): [{"glyph": 409, "name": "floating eye"}],
    ("e", "PET_CLR_WHITE"): [{"glyph": 410, "name": "freezing sphere"}],
    ("e", "PET_CLR_RED"): [{"glyph": 411, "name": "flaming sphere"}],
    ("e", "PET_CLR_BRIGHT_BLUE"): [{"glyph": 412, "name": "shocking sphere"}],
    ("f", "PET_CLR_WHITE"): [
        {"glyph": 413, "name": "kitten"},
        {"glyph": 414, "name": "housecat"},
        {"glyph": 418, "name": "large cat"},
    ],
    ("f", "PET_CLR_BROWN"): [{"glyph": 415, "name": "jaguar"}],
    ("f", "PET_CLR_CYAN"): [{"glyph": 416, "name": "lynx"}],
    ("f", "PET_CLR_BLACK"): [{"glyph": 417, "name": "panther"}],
    ("f", "PET_CLR_YELLOW"): [{"glyph": 419, "name": "tiger"}],
    ("g", "PET_CLR_GREEN"): [{"glyph": 420, "name": "gremlin"}],
    ("g", "PET_CLR_BROWN"): [{"glyph": 421, "name": "gargoyle"}],
    ("g", "PET_CLR_MAGENTA"): [{"glyph": 422, "name": "winged gargoyle"}],
    ("h", "PET_CLR_GREEN"): [{"glyph": 423, "name": "hobbit"}],
    ("h", "PET_CLR_RED"): [{"glyph": 424, "name": "dwarf"}],
    ("h", "PET_CLR_BROWN"): [{"glyph": 425, "name": "bugbear"}],
    ("h", "PET_CLR_BLUE"): [{"glyph": 426, "name": "dwarf lord"}],
    ("h", "PET_CLR_MAGENTA"): [
        {"glyph": 427, "name": "dwarf king"},
        {"glyph": 428, "name": "mind flayer"},
        {"glyph": 429, "name": "master mind flayer"},
    ],
    ("i", "PET_CLR_RED"): [
        {"glyph": 430, "name": "manes"},
        {"glyph": 432, "name": "imp"},
    ],
    ("i", "PET_CLR_GREEN"): [{"glyph": 431, "name": "homunculus"}],
    ("i", "PET_CLR_BROWN"): [{"glyph": 433, "name": "lemure"}],
    ("i", "PET_CLR_BLUE"): [{"glyph": 434, "name": "quasit"}],
    ("i", "PET_CLR_CYAN"): [{"glyph": 435, "name": "tengu"}],
    ("j", "PET_CLR_BLUE"): [{"glyph": 436, "name": "blue jelly"}],
    ("j", "PET_CLR_GREEN"): [{"glyph": 437, "name": "spotted jelly"}],
    ("j", "PET_CLR_BROWN"): [{"glyph": 438, "name": "ochre jelly"}],
    ("k", "PET_CLR_BROWN"): [{"glyph": 439, "name": "kobold"}],
    ("k", "PET_CLR_RED"): [{"glyph": 440, "name": "large kobold"}],
    ("k", "PET_CLR_MAGENTA"): [{"glyph": 441, "name": "kobold lord"}],
    ("k", "PET_CLR_BRIGHT_BLUE"): [{"glyph": 442, "name": "kobold shaman"}],
    ("l", "PET_CLR_GREEN"): [{"glyph": 443, "name": "leprechaun"}],
    ("m", "PET_CLR_BROWN"): [{"glyph": 444, "name": "small mimic"}],
    ("m", "PET_CLR_RED"): [{"glyph": 445, "name": "large mimic"}],
    ("m", "PET_CLR_MAGENTA"): [{"glyph": 446, "name": "giant mimic"}],
    ("n", "PET_CLR_GREEN"): [{"glyph": 447, "name": "wood nymph"}],
    ("n", "PET_CLR_BLUE"): [{"glyph": 448, "name": "water nymph"}],
    ("n", "PET_CLR_BROWN"): [{"glyph": 449, "name": "mountain nymph"}],
    ("o", "PET_CLR_GRAY"): [{"glyph": 450, "name": "goblin"}],
    ("o", "PET_CLR_BROWN"): [{"glyph": 451, "name": "hobgoblin"}],
    ("o", "PET_CLR_RED"): [{"glyph": 452, "name": "orc"}],
    ("o", "PET_CLR_YELLOW"): [{"glyph": 453, "name": "hill orc"}],
    ("o", "PET_CLR_BLUE"): [{"glyph": 454, "name": "Mordor orc"}],
    ("o", "PET_CLR_BLACK"): [{"glyph": 455, "name": "Uruk-hai"}],
    ("o", "PET_CLR_BRIGHT_BLUE"): [{"glyph": 456, "name": "orc shaman"}],
    ("o", "PET_CLR_MAGENTA"): [{"glyph": 457, "name": "orc-captain"}],
    ("p", "PET_CLR_GRAY"): [{"glyph": 458, "name": "rock piercer"}],
    ("p", "PET_CLR_CYAN"): [{"glyph": 459, "name": "iron piercer"}],
    ("p", "PET_CLR_WHITE"): [{"glyph": 460, "name": "glass piercer"}],
    ("q", "PET_CLR_BROWN"): [{"glyph": 461, "name": "rothe"}],
    ("q", "PET_CLR_GRAY"): [
        {"glyph": 462, "name": "mumak"},
        {"glyph": 465, "name": "titanothere"},
        {"glyph": 466, "name": "baluchitherium"},
    ],
    ("q", "PET_CLR_RED"): [{"glyph": 463, "name": "leocrotta"}],
    ("q", "PET_CLR_CYAN"): [{"glyph": 464, "name": "wumpus"}],
    ("q", "PET_CLR_BLACK"): [{"glyph": 467, "name": "mastodon"}],
    ("r", "PET_CLR_BROWN"): [
        {"glyph": 468, "name": "sewer rat"},
        {"glyph": 469, "name": "giant rat"},
        {"glyph": 470, "name": "rabid rat"},
        {"glyph": 471, "name": "wererat"},
        {"glyph": 473, "name": "woodchuck"},
    ],
    ("r", "PET_CLR_GRAY"): [{"glyph": 472, "name": "rock mole"}],
    ("s", "PET_CLR_GRAY"): [{"glyph": 474, "name": "cave spider"}],
    ("s", "PET_CLR_YELLOW"): [{"glyph": 475, "name": "centipede"}],
    ("s", "PET_CLR_MAGENTA"): [
        {"glyph": 476, "name": "giant spider"},
        {"glyph": 743, "name": "Scorpius"},
    ],
    ("s", "PET_CLR_RED"): [{"glyph": 477, "name": "scorpion"}],
    ("t", "PET_CLR_GRAY"): [{"glyph": 478, "name": "lurker above"}],
    ("t", "PET_CLR_GREEN"): [{"glyph": 479, "name": "trapper"}],
    ("u", "PET_CLR_BROWN"): [
        {"glyph": 480, "name": "pony"},
        {"glyph": 484, "name": "horse"},
        {"glyph": 485, "name": "warhorse"},
    ],
    ("u", "PET_CLR_WHITE"): [{"glyph": 481, "name": "white unicorn"}],
    ("u", "PET_CLR_GRAY"): [{"glyph": 482, "name": "gray unicorn"}],
    ("u", "PET_CLR_BLACK"): [{"glyph": 483, "name": "black unicorn"}],
    ("v", "PET_CLR_GRAY"): [{"glyph": 486, "name": "fog cloud"}],
    ("v", "PET_CLR_BROWN"): [{"glyph": 487, "name": "dust vortex"}],
    ("v", "PET_CLR_CYAN"): [{"glyph": 488, "name": "ice vortex"}],
    ("v", "PET_CLR_BRIGHT_BLUE"): [{"glyph": 489, "name": "energy vortex"}],
    ("v", "PET_CLR_BLUE"): [{"glyph": 490, "name": "steam vortex"}],
    ("v", "PET_CLR_YELLOW"): [{"glyph": 491, "name": "fire vortex"}],
    ("w", "PET_CLR_BROWN"): [
        {"glyph": 492, "name": "baby long worm"},
        {"glyph": 494, "name": "long worm"},
    ],
    ("w", "PET_CLR_MAGENTA"): [
        {"glyph": 493, "name": "baby purple worm"},
        {"glyph": 495, "name": "purple worm"},
    ],
    ("x", "PET_CLR_MAGENTA"): [{"glyph": 496, "name": "grid bug"}],
    ("x", "PET_CLR_RED"): [{"glyph": 497, "name": "xan"}],
    ("y", "PET_CLR_YELLOW"): [{"glyph": 498, "name": "yellow light"}],
    ("y", "PET_CLR_BLACK"): [{"glyph": 499, "name": "black light"}],
    ("z", "PET_CLR_BROWN"): [{"glyph": 500, "name": "zruty"}],
    ("A", "PET_CLR_GREEN"): [{"glyph": 501, "name": "couatl"}],
    ("A", "PET_CLR_YELLOW"): [
        {"glyph": 502, "name": "Aleax"},
        {"glyph": 504, "name": "ki-rin"},
    ],
    ("A", "PET_CLR_WHITE"): [{"glyph": 503, "name": "Angel"}],
    ("A", "PET_CLR_MAGENTA"): [{"glyph": 505, "name": "Archon"}],
    ("B", "PET_CLR_BROWN"): [{"glyph": 506, "name": "bat"}],
    ("B", "PET_CLR_RED"): [{"glyph": 507, "name": "giant bat"}],
    ("B", "PET_CLR_BLACK"): [
        {"glyph": 508, "name": "raven"},
        {"glyph": 509, "name": "vampire bat"},
    ],
    ("C", "PET_CLR_BROWN"): [{"glyph": 510, "name": "plains centaur"}],
    ("C", "PET_CLR_GREEN"): [{"glyph": 511, "name": "forest centaur"}],
    ("C", "PET_CLR_CYAN"): [{"glyph": 512, "name": "mountain centaur"}],
    ("D", "PET_CLR_GRAY"): [
        {"glyph": 513, "name": "baby gray dragon"},
        {"glyph": 522, "name": "gray dragon"},
    ],
    ("D", "PET_CLR_BRIGHT_CYAN"): [
        {"glyph": 514, "name": "baby silver dragon"},
        {"glyph": 523, "name": "silver dragon"},
    ],
    ("D", "PET_CLR_RED"): [
        {"glyph": 515, "name": "baby red dragon"},
        {"glyph": 524, "name": "red dragon"},
        {"glyph": 740, "name": "Ixoth"},
    ],
    ("D", "PET_CLR_WHITE"): [
        {"glyph": 516, "name": "baby white dragon"},
        {"glyph": 525, "name": "white dragon"},
    ],
    ("D", "PET_CLR_ORANGE"): [
        {"glyph": 517, "name": "baby orange dragon"},
        {"glyph": 526, "name": "orange dragon"},
    ],
    ("D", "PET_CLR_BLACK"): [
        {"glyph": 518, "name": "baby black dragon"},
        {"glyph": 527, "name": "black dragon"},
    ],
    ("D", "PET_CLR_BLUE"): [
        {"glyph": 519, "name": "baby blue dragon"},
        {"glyph": 528, "name": "blue dragon"},
    ],
    ("D", "PET_CLR_GREEN"): [
        {"glyph": 520, "name": "baby green dragon"},
        {"glyph": 529, "name": "green dragon"},
    ],
    ("D", "PET_CLR_YELLOW"): [
        {"glyph": 521, "name": "baby yellow dragon"},
        {"glyph": 530, "name": "yellow dragon"},
    ],
    ("E", "PET_CLR_WHITE"): [{"glyph": 531, "name": "stalker"}],
    ("E", "PET_CLR_CYAN"): [{"glyph": 532, "name": "air elemental"}],
    ("E", "PET_CLR_YELLOW"): [{"glyph": 533, "name": "fire elemental"}],
    ("E", "PET_CLR_BROWN"): [{"glyph": 534, "name": "earth elemental"}],
    ("E", "PET_CLR_BLUE"): [{"glyph": 535, "name": "water elemental"}],
    ("F", "PET_CLR_BRIGHT_GREEN"): [{"glyph": 536, "name": "lichen"}],
    ("F", "PET_CLR_BROWN"): [{"glyph": 537, "name": "brown mold"}],
    ("F", "PET_CLR_YELLOW"): [{"glyph": 538, "name": "yellow mold"}],
    ("F", "PET_CLR_GREEN"): [{"glyph": 539, "name": "green mold"}],
    ("F", "PET_CLR_RED"): [{"glyph": 540, "name": "red mold"}],
    ("F", "PET_CLR_MAGENTA"): [
        {"glyph": 541, "name": "shrieker"},
        {"glyph": 542, "name": "fungus"},
    ],
    ("G", "PET_CLR_BROWN"): [{"glyph": 543, "name": "gnome"}],
    ("G", "PET_CLR_BLUE"): [{"glyph": 544, "name": "gnome lord"}],
    ("G", "PET_CLR_BRIGHT_BLUE"): [{"glyph": 545, "name": "gnomish wizard"}],
    ("G", "PET_CLR_MAGENTA"): [{"glyph": 546, "name": "gnome king"}],
    ("H", "PET_CLR_RED"): [{"glyph": 547, "name": "giant"}],
    ("H", "PET_CLR_GRAY"): [
        {"glyph": 548, "name": "stone giant"},
        {"glyph": 739, "name": "Cyclops"},
    ],
    ("H", "PET_CLR_CYAN"): [{"glyph": 549, "name": "hill giant"}],
    ("H", "PET_CLR_YELLOW"): [{"glyph": 550, "name": "fire giant"}],
    ("H", "PET_CLR_WHITE"): [{"glyph": 551, "name": "frost giant"}],
    ("H", "PET_CLR_BROWN"): [
        {"glyph": 552, "name": "ettin"},
        {"glyph": 555, "name": "minotaur"},
    ],
    ("H", "PET_CLR_BLUE"): [{"glyph": 553, "name": "storm giant"}],
    ("H", "PET_CLR_MAGENTA"): [
        {"glyph": 554, "name": "titan"},
        {"glyph": 746, "name": "Lord Surtur"},
    ],
    ("I", "PET_CLR_WHITE"): [{"glyph": 380, "name": " it"}],
    ("J", "PET_CLR_ORANGE"): [{"glyph": 556, "name": "jabberwock"}],
    ("K", "PET_CLR_BLUE"): [
        {"glyph": 557, "name": "Keystone Kop"},
        {"glyph": 558, "name": "Kop Sergeant"},
    ],
    ("K", "PET_CLR_CYAN"): [{"glyph": 559, "name": "Kop Lieutenant"}],
    ("K", "PET_CLR_MAGENTA"): [{"glyph": 560, "name": "Kop Kaptain"}],
    ("L", "PET_CLR_BROWN"): [{"glyph": 561, "name": "lich"}],
    ("L", "PET_CLR_RED"): [{"glyph": 562, "name": "demilich"}],
    ("L", "PET_CLR_MAGENTA"): [
        {"glyph": 563, "name": "master lich"},
        {"glyph": 564, "name": "arch-lich"},
    ],
    ("M", "PET_CLR_BROWN"): [{"glyph": 565, "name": "kobold mummy"}],
    ("M", "PET_CLR_RED"): [
        {"glyph": 566, "name": "gnome mummy"},
        {"glyph": 568, "name": "dwarf mummy"},
    ],
    ("M", "PET_CLR_GRAY"): [
        {"glyph": 567, "name": "orc mummy"},
        {"glyph": 570, "name": "human mummy"},
    ],
    ("M", "PET_CLR_GREEN"): [{"glyph": 569, "name": "elf mummy"}],
    ("M", "PET_CLR_BLUE"): [{"glyph": 571, "name": "ettin mummy"}],
    ("M", "PET_CLR_CYAN"): [{"glyph": 572, "name": "giant mummy"}],
    ("N", "PET_CLR_RED"): [
        {"glyph": 573, "name": "red naga hatchling"},
        {"glyph": 577, "name": "red naga"},
    ],
    ("N", "PET_CLR_BLACK"): [
        {"glyph": 574, "name": "black naga hatchling"},
        {"glyph": 578, "name": "black naga"},
    ],
    ("N", "PET_CLR_YELLOW"): [
        {"glyph": 575, "name": "golden naga hatchling"},
        {"glyph": 579, "name": "golden naga"},
    ],
    ("N", "PET_CLR_GREEN"): [
        {"glyph": 576, "name": "guardian naga hatchling"},
        {"glyph": 580, "name": "guardian naga"},
    ],
    ("O", "PET_CLR_BROWN"): [{"glyph": 581, "name": "ogre"}],
    ("O", "PET_CLR_RED"): [{"glyph": 582, "name": "ogre lord"}],
    ("O", "PET_CLR_MAGENTA"): [{"glyph": 583, "name": "ogre king"}],
    ("P", "PET_CLR_GRAY"): [{"glyph": 584, "name": "gray ooze"}],
    ("P", "PET_CLR_BROWN"): [{"glyph": 585, "name": "brown pudding"}],
    ("P", "PET_CLR_GREEN"): [{"glyph": 586, "name": "green slime"}],
    ("P", "PET_CLR_BLACK"): [{"glyph": 587, "name": "black pudding"}],
    ("Q", "PET_CLR_CYAN"): [{"glyph": 588, "name": "quantum mechanic"}],
    ("R", "PET_CLR_BROWN"): [{"glyph": 589, "name": "rust monster"}],
    ("R", "PET_CLR_BLUE"): [{"glyph": 590, "name": "disenchanter"}],
    ("S", "PET_CLR_GREEN"): [{"glyph": 591, "name": "garter snake"}],
    ("S", "PET_CLR_BROWN"): [{"glyph": 592, "name": "snake"}],
    ("S", "PET_CLR_RED"): [{"glyph": 593, "name": "water moccasin"}],
    ("S", "PET_CLR_MAGENTA"): [{"glyph": 594, "name": "python"}],
    ("S", "PET_CLR_BLUE"): [
        {"glyph": 595, "name": "pit viper"},
        {"glyph": 596, "name": "cobra"},
    ],
    ("T", "PET_CLR_BROWN"): [{"glyph": 597, "name": "troll"}],
    ("T", "PET_CLR_WHITE"): [{"glyph": 598, "name": "ice troll"}],
    ("T", "PET_CLR_CYAN"): [{"glyph": 599, "name": "rock troll"}],
    ("T", "PET_CLR_BLUE"): [{"glyph": 600, "name": "water troll"}],
    ("T", "PET_CLR_MAGENTA"): [{"glyph": 601, "name": "Olog-hai"}],
    ("U", "PET_CLR_BROWN"): [{"glyph": 602, "name": "umber hulk"}],
    ("V", "PET_CLR_RED"): [{"glyph": 603, "name": "vampire"}],
    ("V", "PET_CLR_BLUE"): [{"glyph": 604, "name": "vampire lord"}],
    ("V", "PET_CLR_MAGENTA"): [{"glyph": 605, "name": "Vlad the Impaler"}],
    ("W", "PET_CLR_GRAY"): [{"glyph": 606, "name": "barrow wight"}],
    ("W", "PET_CLR_BLACK"): [{"glyph": 607, "name": "wraith"}],
    ("W", "PET_CLR_MAGENTA"): [{"glyph": 608, "name": "Nazgul"}],
    ("X", "PET_CLR_BROWN"): [{"glyph": 609, "name": "xorn"}],
    ("Y", "PET_CLR_GRAY"): [
        {"glyph": 610, "name": "monkey"},
        {"glyph": 615, "name": "sasquatch"},
    ],
    ("Y", "PET_CLR_BROWN"): [
        {"glyph": 611, "name": "ape"},
        {"glyph": 612, "name": "owlbear"},
    ],
    ("Y", "PET_CLR_WHITE"): [{"glyph": 613, "name": "yeti"}],
    ("Y", "PET_CLR_BLACK"): [{"glyph": 614, "name": "carnivorous ape"}],
    ("Z", "PET_CLR_BROWN"): [
        {"glyph": 616, "name": "kobold zombie"},
        {"glyph": 617, "name": "gnome zombie"},
    ],
    ("Z", "PET_CLR_GRAY"): [{"glyph": 618, "name": "orc zombie"}],
    ("Z", "PET_CLR_RED"): [{"glyph": 619, "name": "dwarf zombie"}],
    ("Z", "PET_CLR_GREEN"): [{"glyph": 620, "name": "elf zombie"}],
    ("Z", "PET_CLR_WHITE"): [
        {"glyph": 621, "name": "human zombie"},
        {"glyph": 625, "name": "skeleton"},
    ],
    ("Z", "PET_CLR_BLUE"): [{"glyph": 622, "name": "ettin zombie"}],
    ("Z", "PET_CLR_BLACK"): [{"glyph": 623, "name": "ghoul"}],
    ("Z", "PET_CLR_CYAN"): [{"glyph": 624, "name": "giant zombie"}],
    ("'", "PET_CLR_YELLOW"): [
        {"glyph": 626, "name": "straw golem"},
        {"glyph": 629, "name": "gold golem"},
    ],
    ("'", "PET_CLR_WHITE"): [{"glyph": 627, "name": "paper golem"}],
    ("'", "PET_CLR_BROWN"): [
        {"glyph": 628, "name": "rope golem"},
        {"glyph": 630, "name": "leather golem"},
        {"glyph": 631, "name": "wood golem"},
        {"glyph": 633, "name": "clay golem"},
    ],
    ("'", "PET_CLR_RED"): [{"glyph": 632, "name": "flesh golem"}],
    ("'", "PET_CLR_GRAY"): [{"glyph": 634, "name": "stone golem"}],
    ("'", "PET_CLR_CYAN"): [
        {"glyph": 635, "name": "glass golem"},
        {"glyph": 636, "name": "iron golem"},
    ],
    ("@", "PET_CLR_WHITE"): [
        {"glyph": 637, "name": "human"},
        {"glyph": 641, "name": "elf"},
        {"glyph": 647, "name": "doppelganger"},
        {"glyph": 648, "name": "shopkeeper"},
        {"glyph": 650, "name": "prisoner"},
        {"glyph": 652, "name": "aligned priest"},
        {"glyph": 653, "name": "high priest"},
        {"glyph": 656, "name": "nurse"},
        {"glyph": 708, "name": "archeologist"},
        {"glyph": 709, "name": "barbarian"},
        {"glyph": 710, "name": "caveman"},
        {"glyph": 711, "name": "cavewoman"},
        {"glyph": 712, "name": "healer"},
        {"glyph": 713, "name": "knight"},
        {"glyph": 714, "name": "monk"},
        {"glyph": 715, "name": "priest"},
        {"glyph": 716, "name": "priestess"},
        {"glyph": 717, "name": "ranger"},
        {"glyph": 718, "name": "rogue"},
        {"glyph": 719, "name": "samurai"},
        {"glyph": 720, "name": "tourist"},
        {"glyph": 721, "name": "valkyrie"},
        {"glyph": 722, "name": "wizard"},
        {"glyph": 729, "name": "Arch Priest"},
        {"glyph": 733, "name": "Twoflower"},
        {"glyph": 748, "name": "student"},
        {"glyph": 749, "name": "chieftain"},
        {"glyph": 750, "name": "neanderthal"},
        {"glyph": 751, "name": "attendant"},
        {"glyph": 752, "name": "page"},
        {"glyph": 753, "name": "abbot"},
        {"glyph": 754, "name": "acolyte"},
        {"glyph": 755, "name": "hunter"},
        {"glyph": 756, "name": "thug"},
        {"glyph": 757, "name": "ninja"},
        {"glyph": 758, "name": "roshi"},
        {"glyph": 759, "name": "guide"},
        {"glyph": 760, "name": "warrior"},
        {"glyph": 761, "name": "apprentice"},
    ],
    ("@", "PET_CLR_BROWN"): [{"glyph": 638, "name": "wererat"}],
    ("@", "PET_CLR_RED"): [
        {"glyph": 639, "name": "werejackal"},
        {"glyph": 655, "name": "sergeant"},
    ],
    ("@", "PET_CLR_ORANGE"): [{"glyph": 640, "name": "werewolf"}],
    ("@", "PET_CLR_GREEN"): [
        {"glyph": 642, "name": "Woodland-elf"},
        {"glyph": 657, "name": "lieutenant"},
        {"glyph": 660, "name": "watch captain"},
        {"glyph": 735, "name": "Neferet the Green"},
    ],
    ("@", "PET_CLR_BRIGHT_GREEN"): [
        {"glyph": 643, "name": "Green-elf"},
        {"glyph": 661, "name": "Medusa"},
    ],
    ("@", "PET_CLR_GRAY"): [
        {"glyph": 644, "name": "Grey-elf"},
        {"glyph": 654, "name": "soldier"},
        {"glyph": 659, "name": "watchman"},
    ],
    ("@", "PET_CLR_BRIGHT_BLUE"): [
        {"glyph": 645, "name": "elf-lord"},
        {"glyph": 651, "name": "Oracle"},
    ],
    ("@", "PET_CLR_MAGENTA"): [
        {"glyph": 646, "name": "Elvenking"},
        {"glyph": 662, "name": "Wizard of Yendor"},
        {"glyph": 663, "name": "Croesus"},
        {"glyph": 723, "name": "Lord Carnarvon"},
        {"glyph": 724, "name": "Pelias"},
        {"glyph": 725, "name": "Shaman Karnov"},
        {"glyph": 726, "name": "Hippocrates"},
        {"glyph": 727, "name": "King Arthur"},
        {"glyph": 730, "name": "Orion"},
        {"glyph": 731, "name": "Master of Thieves"},
        {"glyph": 732, "name": "Lord Sato"},
        {"glyph": 734, "name": "Norn"},
        {"glyph": 737, "name": "Thoth Amon"},
        {"glyph": 741, "name": "Master Kaen"},
        {"glyph": 744, "name": "Master Assassin"},
        {"glyph": 745, "name": "Ashikaga Takauji"},
    ],
    ("@", "PET_CLR_BLUE"): [
        {"glyph": 649, "name": "guard"},
        {"glyph": 658, "name": "captain"},
    ],
    ("", "PET_CLR_GRAY"): [{"glyph": 664, "name": "ghost"}],
    ("", "PET_CLR_BLACK"): [{"glyph": 665, "name": "shade"}],
    ("&", "PET_CLR_BLUE"): [{"glyph": 666, "name": "water demon"}],
    ("&", "PET_CLR_GRAY"): [
        {"glyph": 667, "name": "succubus"},
        {"glyph": 669, "name": "incubus"},
        {"glyph": 675, "name": "bone devil"},
        {"glyph": 679, "name": "sandestin"},
    ],
    ("&", "PET_CLR_BROWN"): [{"glyph": 668, "name": "horned devil"}],
    ("&", "PET_CLR_RED"): [
        {"glyph": 670, "name": "erinys"},
        {"glyph": 671, "name": "barbed devil"},
        {"glyph": 672, "name": "marilith"},
        {"glyph": 673, "name": "vrock"},
        {"glyph": 674, "name": "hezrou"},
        {"glyph": 677, "name": "nalfeshnee"},
        {"glyph": 678, "name": "pit fiend"},
        {"glyph": 680, "name": "balrog"},
        {"glyph": 736, "name": "Minion of Huhetotl"},
        {"glyph": 742, "name": "Nalzok"},
    ],
    ("&", "PET_CLR_WHITE"): [{"glyph": 676, "name": "ice devil"}],
    ("&", "PET_CLR_BRIGHT_GREEN"): [{"glyph": 681, "name": "Juiblex"}],
    ("&", "PET_CLR_MAGENTA"): [
        {"glyph": 682, "name": "Yeenoghu"},
        {"glyph": 683, "name": "Orcus"},
        {"glyph": 684, "name": "Geryon"},
        {"glyph": 685, "name": "Dispater"},
        {"glyph": 686, "name": "Baalzebub"},
        {"glyph": 687, "name": "Asmodeus"},
        {"glyph": 688, "name": "Demogorgon"},
        {"glyph": 689, "name": "Death"},
        {"glyph": 690, "name": "Pestilence"},
        {"glyph": 691, "name": "Famine"},
    ],
    ("&", "PET_CLR_YELLOW"): [{"glyph": 692, "name": "djinni"}],
    (";", "PET_CLR_BLUE"): [{"glyph": 693, "name": "jellyfish"}],
    (";", "PET_CLR_RED"): [
        {"glyph": 694, "name": "piranha"},
        {"glyph": 698, "name": "kraken"},
    ],
    (";", "PET_CLR_GRAY"): [{"glyph": 695, "name": "shark"}],
    (";", "PET_CLR_CYAN"): [{"glyph": 696, "name": "giant eel"}],
    (";", "PET_CLR_BRIGHT_BLUE"): [{"glyph": 697, "name": "electric eel"}],
    (":", "PET_CLR_YELLOW"): [{"glyph": 699, "name": "newt"}],
    (":", "PET_CLR_GREEN"): [
        {"glyph": 700, "name": "gecko"},
        {"glyph": 703, "name": "lizard"},
    ],
    (":", "PET_CLR_BROWN"): [
        {"glyph": 701, "name": "iguana"},
        {"glyph": 702, "name": "baby crocodile"},
        {"glyph": 704, "name": "chameleon"},
        {"glyph": 705, "name": "crocodile"},
    ],
    (":", "PET_CLR_ORANGE"): [{"glyph": 706, "name": "salamander"}],
    ("~", "PET_CLR_BROWN"): [{"glyph": 707, "name": "long worm tail"}],
    ("@", "PET_CLR_BLACK"): [
        {"glyph": 728, "name": "Grand Master"},
        {"glyph": 747, "name": "Dark One"},
    ],
    ("D", "PET_CLR_MAGENTA"): [{"glyph": 738, "name": "Chromatic Dragon"}],
}

# PETS_TO_GLYPH is the exact same as MONSTERS_TO_GLYPH, but the difference that the color is
# shifted by 16 up, so we can just copy the values from MONSTERS_TO_GLYPH, and change
# the color to add "MON_" at the beggining of the color name

# for key, monsters in MON_TO_GLYPH.items():
#     for monster in monsters:
#         PETS_TO_GLYPH[(key[0], f"PET_{key[1]}")].append(
#             {"glyph": monster["glyph"] + nh.GLYPH_PET_OFF, "name": monster["name"]}
#         )

# print(PETS_TO_GLYPH)

# TRAP_TO_GLYPH_DICT = defaultdict(list)

# for i in range(nh.MAX_GLYPH):
#     if nh.glyph_is_trap(i):
#         desc = nh.glyph_to_trap(i)

#         if desc == 0 or desc == 24:
#             continue

#         TRAP_TO_GLYPH_DICT[("^", trap_types[str(desc)][1])].append(
#             {
#                 "glyph": i,
#                 "appearance": trap_types[str(desc)][0],
#             }
#         )

# print("TRAP", i, desc, chr(desc))


# print(TRAP_TO_GLYPH_DICT)

# if nh.glyph_is_normal_object(i):
#     obj = nh.objclass(nh.glyph_to_obj(i))
#     appearance = nh.OBJ_DESCR(obj) or nh.OBJ_NAME(obj)
#     oclass = ord(obj.oc_class)
#     desc = f"{i} | {obj_classes[oclass]} | {appearance} | {obj_class_symbols[obj_classes[oclass]]} | {color_dict[obj.oc_color]}"
#     OBJ_TO_GLYPH_DICT[
#         (obj_class_symbols[obj_classes[oclass]], color_dict[obj.oc_color])
#     ].append({"glyph": i, "appearance": appearance, "class": obj_classes[oclass]})
# print(hex(23))
