import functools
import nle.nethack as nh

ALL_MONS = [nh.GLYPH_MON_OFF + i for i in range(nh.NUMMONS)]
ALL_PETS = [nh.GLYPH_PET_OFF + i for i in range(nh.NUMMONS)]

monsters_list = [
    (0, "giant ant", "a", 3),
    (1, "killer bee", "a", 11),
    (2, "soldier ant", "a", 4),
    (3, "fire ant", "a", 1),
    (4, "giant beetle", "a", 0),
    (5, "queen bee", "a", 5),
    (6, "acid blob", "b", 2),
    (7, "quivering blob", "b", 15),
    (8, "gelatinous cube", "b", 6),
    (9, "chickatrice", "c", 3),
    (10, "cockatrice", "c", 11),
    (11, "pyrolisk", "c", 1),
    (12, "jackal", "d", 3),
    (13, "fox", "d", 1),
    (14, "coyote", "d", 3),
    (15, "werejackal", "d", 3),
    (16, "little dog", "d", 15),
    (17, "dingo", "d", 11),
    (18, "dog", "d", 15),
    (19, "large dog", "d", 15),
    (20, "wolf", "d", 3),
    (21, "werewolf", "d", 3),
    (22, "winter wolf cub", "d", 6),
    (23, "warg", "d", 3),
    (24, "winter wolf", "d", 6),
    (25, "hell hound pup", "d", 1),
    (26, "hell hound", "d", 1),
    (27, "gas spore", "e", 7),
    (28, "floating eye", "e", 4),
    (29, "freezing sphere", "e", 15),
    (30, "flaming sphere", "e", 1),
    (31, "shocking sphere", "e", 12),
    (32, "kitten", "f", 15),
    (33, "housecat", "f", 15),
    (34, "jaguar", "f", 3),
    (35, "lynx", "f", 6),
    (36, "panther", "f", 0),
    (37, "large cat", "f", 15),
    (38, "tiger", "f", 11),
    (39, "gremlin", "g", 2),
    (40, "gargoyle", "g", 3),
    (41, "winged gargoyle", "g", 5),
    (42, "hobbit", "h", 2),
    (43, "dwarf", "h", 1),
    (44, "bugbear", "h", 3),
    (45, "dwarf lord", "h", 4),
    (46, "dwarf king", "h", 5),
    (47, "mind flayer", "h", 5),
    (48, "master mind flayer", "h", 5),
    (49, "manes", "i", 1),
    (50, "homunculus", "i", 2),
    (51, "imp", "i", 1),
    (52, "lemure", "i", 3),
    (53, "quasit", "i", 4),
    (54, "tengu", "i", 6),
    (55, "blue jelly", "j", 4),
    (56, "spotted jelly", "j", 2),
    (57, "ochre jelly", "j", 3),
    (58, "kobold", "k", 3),
    (59, "large kobold", "k", 1),
    (60, "kobold lord", "k", 5),
    (61, "kobold shaman", "k", 12),
    (62, "leprechaun", "l", 2),
    (63, "small mimic", "m", 3),
    (64, "large mimic", "m", 1),
    (65, "giant mimic", "m", 5),
    (66, "wood nymph", "n", 2),
    (67, "water nymph", "n", 4),
    (68, "mountain nymph", "n", 3),
    (69, "goblin", "o", 7),
    (70, "hobgoblin", "o", 3),
    (71, "orc", "o", 1),
    (72, "hill orc", "o", 11),
    (73, "Mordor orc", "o", 4),
    (74, "Uruk-hai", "o", 0),
    (75, "orc shaman", "o", 12),
    (76, "orc-captain", "o", 5),
    (77, "rock piercer", "p", 7),
    (78, "iron piercer", "p", 6),
    (79, "glass piercer", "p", 15),
    (80, "rothe", "q", 3),
    (81, "mumak", "q", 7),
    (82, "leocrotta", "q", 1),
    (83, "wumpus", "q", 6),
    (84, "titanothere", "q", 7),
    (85, "baluchitherium", "q", 7),
    (86, "mastodon", "q", 0),
    (87, "sewer rat", "r", 3),
    (88, "giant rat", "r", 3),
    (89, "rabid rat", "r", 3),
    (90, "wererat", "r", 3),
    (91, "rock mole", "r", 7),
    (92, "woodchuck", "r", 3),
    (93, "cave spider", "s", 7),
    (94, "centipede", "s", 11),
    (95, "giant spider", "s", 5),
    (96, "scorpion", "s", 1),
    (97, "lurker above", "t", 7),
    (98, "trapper", "t", 2),
    (99, "pony", "u", 3),
    (100, "white unicorn", "u", 15),
    (101, "gray unicorn", "u", 7),
    (102, "black unicorn", "u", 0),
    (103, "horse", "u", 3),
    (104, "warhorse", "u", 3),
    (105, "fog cloud", "v", 7),
    (106, "dust vortex", "v", 3),
    (107, "ice vortex", "v", 6),
    (108, "energy vortex", "v", 12),
    (109, "steam vortex", "v", 4),
    (110, "fire vortex", "v", 11),
    (111, "baby long worm", "w", 3),
    (112, "baby purple worm", "w", 5),
    (113, "long worm", "w", 3),
    (114, "purple worm", "w", 5),
    (115, "grid bug", "x", 5),
    (116, "xan", "x", 1),
    (117, "yellow light", "y", 11),
    (118, "black light", "y", 0),
    (119, "zruty", "z", 3),
    (120, "couatl", "A", 2),
    (121, "Aleax", "A", 11),
    (122, "Angel", "A", 15),
    (123, "ki-rin", "A", 11),
    (124, "Archon", "A", 5),
    (125, "bat", "B", 3),
    (126, "giant bat", "B", 1),
    (127, "raven", "B", 0),
    (128, "vampire bat", "B", 0),
    (129, "plains centaur", "C", 3),
    (130, "forest centaur", "C", 2),
    (131, "mountain centaur", "C", 6),
    (132, "baby gray dragon", "D", 7),
    (133, "baby silver dragon", "D", 14),
    (134, "baby red dragon", "D", 1),
    (135, "baby white dragon", "D", 15),
    (136, "baby orange dragon", "D", 9),
    (137, "baby black dragon", "D", 0),
    (138, "baby blue dragon", "D", 4),
    (139, "baby green dragon", "D", 2),
    (140, "baby yellow dragon", "D", 11),
    (141, "gray dragon", "D", 7),
    (142, "silver dragon", "D", 14),
    (143, "red dragon", "D", 1),
    (144, "white dragon", "D", 15),
    (145, "orange dragon", "D", 9),
    (146, "black dragon", "D", 0),
    (147, "blue dragon", "D", 4),
    (148, "green dragon", "D", 2),
    (149, "yellow dragon", "D", 11),
    (150, "stalker", "E", 15),
    (151, "air elemental", "E", 6),
    (152, "fire elemental", "E", 11),
    (153, "earth elemental", "E", 3),
    (154, "water elemental", "E", 4),
    (155, "lichen", "F", 10),
    (156, "brown mold", "F", 3),
    (157, "yellow mold", "F", 11),
    (158, "green mold", "F", 2),
    (159, "red mold", "F", 1),
    (160, "shrieker", "F", 5),
    (161, "fungus", "F", 5),
    (162, "gnome", "G", 3),
    (163, "gnome lord", "G", 4),
    (164, "gnomish wizard", "G", 12),
    (165, "gnome king", "G", 5),
    (166, "giant", "H", 1),
    (167, "stone giant", "H", 7),
    (168, "hill giant", "H", 6),
    (169, "fire giant", "H", 11),
    (170, "frost giant", "H", 15),
    (171, "ettin", "H", 3),
    (172, "storm giant", "H", 4),
    (173, "titan", "H", 5),
    (174, "minotaur", "H", 3),
    (-1, " it", "I", 15),  # Unsure of what is its glyph...
    (175, "jabberwock", "J", 9),
    (176, "Keystone Kop", "K", 4),
    (177, "Kop Sergeant", "K", 4),
    (178, "Kop Lieutenant", "K", 6),
    (179, "Kop Kaptain", "K", 5),
    (180, "lich", "L", 3),
    (181, "demilich", "L", 1),
    (182, "master lich", "L", 5),
    (183, "arch-lich", "L", 5),
    (184, "kobold mummy", "M", 3),
    (185, "gnome mummy", "M", 1),
    (186, "orc mummy", "M", 7),
    (187, "dwarf mummy", "M", 1),
    (188, "elf mummy", "M", 2),
    (189, "human mummy", "M", 7),
    (190, "ettin mummy", "M", 4),
    (191, "giant mummy", "M", 6),
    (192, "red naga hatchling", "N", 1),
    (193, "black naga hatchling", "N", 0),
    (194, "golden naga hatchling", "N", 11),
    (195, "guardian naga hatchling", "N", 2),
    (196, "red naga", "N", 1),
    (197, "black naga", "N", 0),
    (198, "golden naga", "N", 11),
    (199, "guardian naga", "N", 2),
    (200, "ogre", "O", 3),
    (201, "ogre lord", "O", 1),
    (202, "ogre king", "O", 5),
    (203, "gray ooze", "P", 7),
    (204, "brown pudding", "P", 3),
    (205, "green slime", "P", 2),
    (206, "black pudding", "P", 0),
    (207, "quantum mechanic", "Q", 6),
    (208, "rust monster", "R", 3),
    (209, "disenchanter", "R", 4),
    (210, "garter snake", "S", 2),
    (211, "snake", "S", 3),
    (212, "water moccasin", "S", 1),
    (213, "python", "S", 5),
    (214, "pit viper", "S", 4),
    (215, "cobra", "S", 4),
    (216, "troll", "T", 3),
    (217, "ice troll", "T", 15),
    (218, "rock troll", "T", 6),
    (219, "water troll", "T", 4),
    (220, "Olog-hai", "T", 5),
    (221, "umber hulk", "U", 3),
    (222, "vampire", "V", 1),
    (223, "vampire lord", "V", 4),
    (224, "Vlad the Impaler", "V", 5),
    (225, "barrow wight", "W", 7),
    (226, "wraith", "W", 0),
    (227, "Nazgul", "W", 5),
    (228, "xorn", "X", 3),
    (229, "monkey", "Y", 7),
    (230, "ape", "Y", 3),
    (231, "owlbear", "Y", 3),
    (232, "yeti", "Y", 15),
    (233, "carnivorous ape", "Y", 0),
    (234, "sasquatch", "Y", 7),
    (235, "kobold zombie", "Z", 3),
    (236, "gnome zombie", "Z", 3),
    (237, "orc zombie", "Z", 7),
    (238, "dwarf zombie", "Z", 1),
    (239, "elf zombie", "Z", 2),
    (240, "human zombie", "Z", 15),
    (241, "ettin zombie", "Z", 4),
    (242, "ghoul", "Z", 0),
    (243, "giant zombie", "Z", 6),
    (244, "skeleton", "Z", 15),
    (245, "straw golem", "'", 11),
    (246, "paper golem", "'", 15),
    (247, "rope golem", "'", 3),
    (248, "gold golem", "'", 11),
    (249, "leather golem", "'", 3),
    (250, "wood golem", "'", 3),
    (251, "flesh golem", "'", 1),
    (252, "clay golem", "'", 3),
    (253, "stone golem", "'", 7),
    (254, "glass golem", "'", 6),
    (255, "iron golem", "'", 6),
    (256, "human", "@", 15),
    (257, "wererat", "@", 3),
    (258, "werejackal", "@", 1),
    (259, "werewolf", "@", 9),
    (260, "elf", "@", 15),
    (261, "Woodland-elf", "@", 2),
    (262, "Green-elf", "@", 10),
    (263, "Grey-elf", "@", 7),
    (264, "elf-lord", "@", 12),
    (265, "Elvenking", "@", 5),
    (266, "doppelganger", "@", 15),
    (267, "shopkeeper", "@", 15),
    (268, "guard", "@", 4),
    (269, "prisoner", "@", 15),
    (270, "Oracle", "@", 12),
    (271, "aligned priest", "@", 15),
    (272, "high priest", "@", 15),
    (273, "soldier", "@", 7),
    (274, "sergeant", "@", 1),
    (275, "nurse", "@", 15),
    (276, "lieutenant", "@", 2),
    (277, "captain", "@", 4),
    (278, "watchman", "@", 7),
    (279, "watch captain", "@", 2),
    (280, "Medusa", "@", 10),
    (281, "Wizard of Yendor", "@", 5),
    (282, "Croesus", "@", 5),
    (283, "ghost", "", 7),
    (284, "shade", "", 0),
    (285, "water demon", "&", 4),
    (286, "succubus", "&", 7),
    (287, "horned devil", "&", 3),
    (288, "incubus", "&", 7),
    (289, "erinys", "&", 1),
    (290, "barbed devil", "&", 1),
    (291, "marilith", "&", 1),
    (292, "vrock", "&", 1),
    (293, "hezrou", "&", 1),
    (294, "bone devil", "&", 7),
    (295, "ice devil", "&", 15),
    (296, "nalfeshnee", "&", 1),
    (297, "pit fiend", "&", 1),
    (298, "sandestin", "&", 7),
    (299, "balrog", "&", 1),
    (300, "Juiblex", "&", 10),
    (301, "Yeenoghu", "&", 5),
    (302, "Orcus", "&", 5),
    (303, "Geryon", "&", 5),
    (304, "Dispater", "&", 5),
    (305, "Baalzebub", "&", 5),
    (306, "Asmodeus", "&", 5),
    (307, "Demogorgon", "&", 5),
    (308, "Death", "&", 5),
    (309, "Pestilence", "&", 5),
    (310, "Famine", "&", 5),
    (311, "djinni", "&", 11),
    (312, "jellyfish", ";", 4),
    (313, "piranha", ";", 1),
    (314, "shark", ";", 7),
    (315, "giant eel", ";", 6),
    (316, "electric eel", ";", 12),
    (317, "kraken", ";", 1),
    (318, "newt", ":", 11),
    (319, "gecko", ":", 2),
    (320, "iguana", ":", 3),
    (321, "baby crocodile", ":", 3),
    (322, "lizard", ":", 2),
    (323, "chameleon", ":", 3),
    (324, "crocodile", ":", 3),
    (325, "salamander", ":", 9),
    (326, "long worm tail", "~", 3),
    (327, "archeologist", "@", 15),
    (328, "barbarian", "@", 15),
    (329, "caveman", "@", 15),
    (330, "cavewoman", "@", 15),
    (331, "healer", "@", 15),
    (332, "knight", "@", 15),
    (333, "monk", "@", 15),
    (334, "priest", "@", 15),
    (335, "priestess", "@", 15),
    (336, "ranger", "@", 15),
    (337, "rogue", "@", 15),
    (338, "samurai", "@", 15),
    (339, "tourist", "@", 15),
    (340, "valkyrie", "@", 15),
    (341, "wizard", "@", 15),
    (342, "Lord Carnarvon", "@", 5),
    (343, "Pelias", "@", 5),
    (344, "Shaman Karnov", "@", 5),
    (345, "Hippocrates", "@", 5),
    (346, "King Arthur", "@", 5),
    (347, "Grand Master", "@", 0),
    (348, "Arch Priest", "@", 15),
    (349, "Orion", "@", 5),
    (350, "Master of Thieves", "@", 5),
    (351, "Lord Sato", "@", 5),
    (352, "Twoflower", "@", 15),
    (353, "Norn", "@", 5),
    (354, "Neferet the Green", "@", 2),
    (355, "Minion of Huhetotl", "&", 1),
    (356, "Thoth Amon", "@", 5),
    (357, "Chromatic Dragon", "D", 5),
    (358, "Cyclops", "H", 7),
    (359, "Ixoth", "D", 1),
    (360, "Master Kaen", "@", 5),
    (361, "Nalzok", "&", 1),
    (362, "Scorpius", "s", 5),
    (363, "Master Assassin", "@", 5),
    (364, "Ashikaga Takauji", "@", 5),
    (365, "Lord Surtur", "H", 5),
    (366, "Dark One", "@", 0),
    (367, "student", "@", 15),
    (368, "chieftain", "@", 15),
    (369, "neanderthal", "@", 15),
    (370, "attendant", "@", 15),
    (371, "page", "@", 15),
    (372, "abbot", "@", 15),
    (373, "acolyte", "@", 15),
    (374, "hunter", "@", 15),
    (375, "thug", "@", 15),
    (376, "ninja", "@", 15),
    (377, "roshi", "@", 15),
    (378, "guide", "@", 15),
    (379, "warrior", "@", 15),
    (380, "apprentice", "@", 15),
]

mapping_dict = {
    ("a", "CLR_BROWN"): [{"glyph": 0, "name": "giant ant"}],
    ("a", "CLR_YELLOW"): [{"glyph": 1, "name": "killer bee"}],
    ("a", "CLR_BLUE"): [{"glyph": 2, "name": "soldier ant"}],
    ("a", "CLR_RED"): [{"glyph": 3, "name": "fire ant"}],
    ("a", "CLR_BLACK"): [{"glyph": 4, "name": "giant beetle"}],
    ("a", "CLR_MAGENTA"): [{"glyph": 5, "name": "queen bee"}],
    ("b", "CLR_GREEN"): [{"glyph": 6, "name": "acid blob"}],
    ("b", "CLR_WHITE"): [{"glyph": 7, "name": "quivering blob"}],
    ("b", "CLR_CYAN"): [{"glyph": 8, "name": "gelatinous cube"}],
    ("c", "CLR_BROWN"): [{"glyph": 9, "name": "chickatrice"}],
    ("c", "CLR_YELLOW"): [{"glyph": 10, "name": "cockatrice"}],
    ("c", "CLR_RED"): [{"glyph": 11, "name": "pyrolisk"}],
    ("d", "CLR_BROWN"): [
        {"glyph": 12, "name": "jackal"},
        {"glyph": 14, "name": "coyote"},
        {"glyph": 15, "name": "werejackal"},
        {"glyph": 20, "name": "wolf"},
        {"glyph": 21, "name": "werewolf"},
        {"glyph": 23, "name": "warg"},
    ],
    ("d", "CLR_RED"): [
        {"glyph": 13, "name": "fox"},
        {"glyph": 25, "name": "hell hound pup"},
        {"glyph": 26, "name": "hell hound"},
    ],
    ("d", "CLR_WHITE"): [
        {"glyph": 16, "name": "little dog"},
        {"glyph": 18, "name": "dog"},
        {"glyph": 19, "name": "large dog"},
    ],
    ("d", "CLR_YELLOW"): [{"glyph": 17, "name": "dingo"}],
    ("d", "CLR_CYAN"): [
        {"glyph": 22, "name": "winter wolf cub"},
        {"glyph": 24, "name": "winter wolf"},
    ],
    ("e", "CLR_GRAY"): [{"glyph": 27, "name": "gas spore"}],
    ("e", "CLR_BLUE"): [{"glyph": 28, "name": "floating eye"}],
    ("e", "CLR_WHITE"): [{"glyph": 29, "name": "freezing sphere"}],
    ("e", "CLR_RED"): [{"glyph": 30, "name": "flaming sphere"}],
    ("e", "CLR_BRIGHT_BLUE"): [{"glyph": 31, "name": "shocking sphere"}],
    ("f", "CLR_WHITE"): [
        {"glyph": 32, "name": "kitten"},
        {"glyph": 33, "name": "housecat"},
        {"glyph": 37, "name": "large cat"},
    ],
    ("f", "CLR_BROWN"): [{"glyph": 34, "name": "jaguar"}],
    ("f", "CLR_CYAN"): [{"glyph": 35, "name": "lynx"}],
    ("f", "CLR_BLACK"): [{"glyph": 36, "name": "panther"}],
    ("f", "CLR_YELLOW"): [{"glyph": 38, "name": "tiger"}],
    ("g", "CLR_GREEN"): [{"glyph": 39, "name": "gremlin"}],
    ("g", "CLR_BROWN"): [{"glyph": 40, "name": "gargoyle"}],
    ("g", "CLR_MAGENTA"): [{"glyph": 41, "name": "winged gargoyle"}],
    ("h", "CLR_GREEN"): [{"glyph": 42, "name": "hobbit"}],
    ("h", "CLR_RED"): [{"glyph": 43, "name": "dwarf"}],
    ("h", "CLR_BROWN"): [{"glyph": 44, "name": "bugbear"}],
    ("h", "CLR_BLUE"): [{"glyph": 45, "name": "dwarf lord"}],
    ("h", "CLR_MAGENTA"): [
        {"glyph": 46, "name": "dwarf king"},
        {"glyph": 47, "name": "mind flayer"},
        {"glyph": 48, "name": "master mind flayer"},
    ],
    ("i", "CLR_RED"): [{"glyph": 49, "name": "manes"}, {"glyph": 51, "name": "imp"}],
    ("i", "CLR_GREEN"): [{"glyph": 50, "name": "homunculus"}],
    ("i", "CLR_BROWN"): [{"glyph": 52, "name": "lemure"}],
    ("i", "CLR_BLUE"): [{"glyph": 53, "name": "quasit"}],
    ("i", "CLR_CYAN"): [{"glyph": 54, "name": "tengu"}],
    ("j", "CLR_BLUE"): [{"glyph": 55, "name": "blue jelly"}],
    ("j", "CLR_GREEN"): [{"glyph": 56, "name": "spotted jelly"}],
    ("j", "CLR_BROWN"): [{"glyph": 57, "name": "ochre jelly"}],
    ("k", "CLR_BROWN"): [{"glyph": 58, "name": "kobold"}],
    ("k", "CLR_RED"): [{"glyph": 59, "name": "large kobold"}],
    ("k", "CLR_MAGENTA"): [{"glyph": 60, "name": "kobold lord"}],
    ("k", "CLR_BRIGHT_BLUE"): [{"glyph": 61, "name": "kobold shaman"}],
    ("l", "CLR_GREEN"): [{"glyph": 62, "name": "leprechaun"}],
    ("m", "CLR_BROWN"): [{"glyph": 63, "name": "small mimic"}],
    ("m", "CLR_RED"): [{"glyph": 64, "name": "large mimic"}],
    ("m", "CLR_MAGENTA"): [{"glyph": 65, "name": "giant mimic"}],
    ("n", "CLR_GREEN"): [{"glyph": 66, "name": "wood nymph"}],
    ("n", "CLR_BLUE"): [{"glyph": 67, "name": "water nymph"}],
    ("n", "CLR_BROWN"): [{"glyph": 68, "name": "mountain nymph"}],
    ("o", "CLR_GRAY"): [{"glyph": 69, "name": "goblin"}],
    ("o", "CLR_BROWN"): [{"glyph": 70, "name": "hobgoblin"}],
    ("o", "CLR_RED"): [{"glyph": 71, "name": "orc"}],
    ("o", "CLR_YELLOW"): [{"glyph": 72, "name": "hill orc"}],
    ("o", "CLR_BLUE"): [{"glyph": 73, "name": "Mordor orc"}],
    ("o", "CLR_BLACK"): [{"glyph": 74, "name": "Uruk-hai"}],
    ("o", "CLR_BRIGHT_BLUE"): [{"glyph": 75, "name": "orc shaman"}],
    ("o", "CLR_MAGENTA"): [{"glyph": 76, "name": "orc-captain"}],
    ("p", "CLR_GRAY"): [{"glyph": 77, "name": "rock piercer"}],
    ("p", "CLR_CYAN"): [{"glyph": 78, "name": "iron piercer"}],
    ("p", "CLR_WHITE"): [{"glyph": 79, "name": "glass piercer"}],
    ("q", "CLR_BROWN"): [{"glyph": 80, "name": "rothe"}],
    ("q", "CLR_GRAY"): [
        {"glyph": 81, "name": "mumak"},
        {"glyph": 84, "name": "titanothere"},
        {"glyph": 85, "name": "baluchitherium"},
    ],
    ("q", "CLR_RED"): [{"glyph": 82, "name": "leocrotta"}],
    ("q", "CLR_CYAN"): [{"glyph": 83, "name": "wumpus"}],
    ("q", "CLR_BLACK"): [{"glyph": 86, "name": "mastodon"}],
    ("r", "CLR_BROWN"): [
        {"glyph": 87, "name": "sewer rat"},
        {"glyph": 88, "name": "giant rat"},
        {"glyph": 89, "name": "rabid rat"},
        {"glyph": 90, "name": "wererat"},
        {"glyph": 92, "name": "woodchuck"},
    ],
    ("r", "CLR_GRAY"): [{"glyph": 91, "name": "rock mole"}],
    ("s", "CLR_GRAY"): [{"glyph": 93, "name": "cave spider"}],
    ("s", "CLR_YELLOW"): [{"glyph": 94, "name": "centipede"}],
    ("s", "CLR_MAGENTA"): [
        {"glyph": 95, "name": "giant spider"},
        {"glyph": 362, "name": "Scorpius"},
    ],
    ("s", "CLR_RED"): [{"glyph": 96, "name": "scorpion"}],
    ("t", "CLR_GRAY"): [{"glyph": 97, "name": "lurker above"}],
    ("t", "CLR_GREEN"): [{"glyph": 98, "name": "trapper"}],
    ("u", "CLR_BROWN"): [
        {"glyph": 99, "name": "pony"},
        {"glyph": 103, "name": "horse"},
        {"glyph": 104, "name": "warhorse"},
    ],
    ("u", "CLR_WHITE"): [{"glyph": 100, "name": "white unicorn"}],
    ("u", "CLR_GRAY"): [{"glyph": 101, "name": "gray unicorn"}],
    ("u", "CLR_BLACK"): [{"glyph": 102, "name": "black unicorn"}],
    ("v", "CLR_GRAY"): [{"glyph": 105, "name": "fog cloud"}],
    ("v", "CLR_BROWN"): [{"glyph": 106, "name": "dust vortex"}],
    ("v", "CLR_CYAN"): [{"glyph": 107, "name": "ice vortex"}],
    ("v", "CLR_BRIGHT_BLUE"): [{"glyph": 108, "name": "energy vortex"}],
    ("v", "CLR_BLUE"): [{"glyph": 109, "name": "steam vortex"}],
    ("v", "CLR_YELLOW"): [{"glyph": 110, "name": "fire vortex"}],
    ("w", "CLR_BROWN"): [
        {"glyph": 111, "name": "baby long worm"},
        {"glyph": 113, "name": "long worm"},
    ],
    ("w", "CLR_MAGENTA"): [
        {"glyph": 112, "name": "baby purple worm"},
        {"glyph": 114, "name": "purple worm"},
    ],
    ("x", "CLR_MAGENTA"): [{"glyph": 115, "name": "grid bug"}],
    ("x", "CLR_RED"): [{"glyph": 116, "name": "xan"}],
    ("y", "CLR_YELLOW"): [{"glyph": 117, "name": "yellow light"}],
    ("y", "CLR_BLACK"): [{"glyph": 118, "name": "black light"}],
    ("z", "CLR_BROWN"): [{"glyph": 119, "name": "zruty"}],
    ("A", "CLR_GREEN"): [{"glyph": 120, "name": "couatl"}],
    ("A", "CLR_YELLOW"): [
        {"glyph": 121, "name": "Aleax"},
        {"glyph": 123, "name": "ki-rin"},
    ],
    ("A", "CLR_WHITE"): [{"glyph": 122, "name": "Angel"}],
    ("A", "CLR_MAGENTA"): [{"glyph": 124, "name": "Archon"}],
    ("B", "CLR_BROWN"): [{"glyph": 125, "name": "bat"}],
    ("B", "CLR_RED"): [{"glyph": 126, "name": "giant bat"}],
    ("B", "CLR_BLACK"): [
        {"glyph": 127, "name": "raven"},
        {"glyph": 128, "name": "vampire bat"},
    ],
    ("C", "CLR_BROWN"): [{"glyph": 129, "name": "plains centaur"}],
    ("C", "CLR_GREEN"): [{"glyph": 130, "name": "forest centaur"}],
    ("C", "CLR_CYAN"): [{"glyph": 131, "name": "mountain centaur"}],
    ("D", "CLR_GRAY"): [
        {"glyph": 132, "name": "baby gray dragon"},
        {"glyph": 141, "name": "gray dragon"},
    ],
    ("D", "CLR_BRIGHT_CYAN"): [
        {"glyph": 133, "name": "baby silver dragon"},
        {"glyph": 142, "name": "silver dragon"},
    ],
    ("D", "CLR_RED"): [
        {"glyph": 134, "name": "baby red dragon"},
        {"glyph": 143, "name": "red dragon"},
        {"glyph": 359, "name": "Ixoth"},
    ],
    ("D", "CLR_WHITE"): [
        {"glyph": 135, "name": "baby white dragon"},
        {"glyph": 144, "name": "white dragon"},
    ],
    ("D", "CLR_ORANGE"): [
        {"glyph": 136, "name": "baby orange dragon"},
        {"glyph": 145, "name": "orange dragon"},
    ],
    ("D", "CLR_BLACK"): [
        {"glyph": 137, "name": "baby black dragon"},
        {"glyph": 146, "name": "black dragon"},
    ],
    ("D", "CLR_BLUE"): [
        {"glyph": 138, "name": "baby blue dragon"},
        {"glyph": 147, "name": "blue dragon"},
    ],
    ("D", "CLR_GREEN"): [
        {"glyph": 139, "name": "baby green dragon"},
        {"glyph": 148, "name": "green dragon"},
    ],
    ("D", "CLR_YELLOW"): [
        {"glyph": 140, "name": "baby yellow dragon"},
        {"glyph": 149, "name": "yellow dragon"},
    ],
    ("E", "CLR_WHITE"): [{"glyph": 150, "name": "stalker"}],
    ("E", "CLR_CYAN"): [{"glyph": 151, "name": "air elemental"}],
    ("E", "CLR_YELLOW"): [{"glyph": 152, "name": "fire elemental"}],
    ("E", "CLR_BROWN"): [{"glyph": 153, "name": "earth elemental"}],
    ("E", "CLR_BLUE"): [{"glyph": 154, "name": "water elemental"}],
    ("F", "CLR_BRIGHT_GREEN"): [{"glyph": 155, "name": "lichen"}],
    ("F", "CLR_BROWN"): [{"glyph": 156, "name": "brown mold"}],
    ("F", "CLR_YELLOW"): [{"glyph": 157, "name": "yellow mold"}],
    ("F", "CLR_GREEN"): [{"glyph": 158, "name": "green mold"}],
    ("F", "CLR_RED"): [{"glyph": 159, "name": "red mold"}],
    ("F", "CLR_MAGENTA"): [
        {"glyph": 160, "name": "shrieker"},
        {"glyph": 161, "name": "fungus"},
    ],
    ("G", "CLR_BROWN"): [{"glyph": 162, "name": "gnome"}],
    ("G", "CLR_BLUE"): [{"glyph": 163, "name": "gnome lord"}],
    ("G", "CLR_BRIGHT_BLUE"): [{"glyph": 164, "name": "gnomish wizard"}],
    ("G", "CLR_MAGENTA"): [{"glyph": 165, "name": "gnome king"}],
    ("H", "CLR_RED"): [{"glyph": 166, "name": "giant"}],
    ("H", "CLR_GRAY"): [
        {"glyph": 167, "name": "stone giant"},
        {"glyph": 358, "name": "Cyclops"},
    ],
    ("H", "CLR_CYAN"): [{"glyph": 168, "name": "hill giant"}],
    ("H", "CLR_YELLOW"): [{"glyph": 169, "name": "fire giant"}],
    ("H", "CLR_WHITE"): [{"glyph": 170, "name": "frost giant"}],
    ("H", "CLR_BROWN"): [
        {"glyph": 171, "name": "ettin"},
        {"glyph": 174, "name": "minotaur"},
    ],
    ("H", "CLR_BLUE"): [{"glyph": 172, "name": "storm giant"}],
    ("H", "CLR_MAGENTA"): [
        {"glyph": 173, "name": "titan"},
        {"glyph": 365, "name": "Lord Surtur"},
    ],
    ("I", "CLR_WHITE"): [{"glyph": -1, "name": " it"}],
    ("J", "CLR_ORANGE"): [{"glyph": 175, "name": "jabberwock"}],
    ("K", "CLR_BLUE"): [
        {"glyph": 176, "name": "Keystone Kop"},
        {"glyph": 177, "name": "Kop Sergeant"},
    ],
    ("K", "CLR_CYAN"): [{"glyph": 178, "name": "Kop Lieutenant"}],
    ("K", "CLR_MAGENTA"): [{"glyph": 179, "name": "Kop Kaptain"}],
    ("L", "CLR_BROWN"): [{"glyph": 180, "name": "lich"}],
    ("L", "CLR_RED"): [{"glyph": 181, "name": "demilich"}],
    ("L", "CLR_MAGENTA"): [
        {"glyph": 182, "name": "master lich"},
        {"glyph": 183, "name": "arch-lich"},
    ],
    ("M", "CLR_BROWN"): [{"glyph": 184, "name": "kobold mummy"}],
    ("M", "CLR_RED"): [
        {"glyph": 185, "name": "gnome mummy"},
        {"glyph": 187, "name": "dwarf mummy"},
    ],
    ("M", "CLR_GRAY"): [
        {"glyph": 186, "name": "orc mummy"},
        {"glyph": 189, "name": "human mummy"},
    ],
    ("M", "CLR_GREEN"): [{"glyph": 188, "name": "elf mummy"}],
    ("M", "CLR_BLUE"): [{"glyph": 190, "name": "ettin mummy"}],
    ("M", "CLR_CYAN"): [{"glyph": 191, "name": "giant mummy"}],
    ("N", "CLR_RED"): [
        {"glyph": 192, "name": "red naga hatchling"},
        {"glyph": 196, "name": "red naga"},
    ],
    ("N", "CLR_BLACK"): [
        {"glyph": 193, "name": "black naga hatchling"},
        {"glyph": 197, "name": "black naga"},
    ],
    ("N", "CLR_YELLOW"): [
        {"glyph": 194, "name": "golden naga hatchling"},
        {"glyph": 198, "name": "golden naga"},
    ],
    ("N", "CLR_GREEN"): [
        {"glyph": 195, "name": "guardian naga hatchling"},
        {"glyph": 199, "name": "guardian naga"},
    ],
    ("O", "CLR_BROWN"): [{"glyph": 200, "name": "ogre"}],
    ("O", "CLR_RED"): [{"glyph": 201, "name": "ogre lord"}],
    ("O", "CLR_MAGENTA"): [{"glyph": 202, "name": "ogre king"}],
    ("P", "CLR_GRAY"): [{"glyph": 203, "name": "gray ooze"}],
    ("P", "CLR_BROWN"): [{"glyph": 204, "name": "brown pudding"}],
    ("P", "CLR_GREEN"): [{"glyph": 205, "name": "green slime"}],
    ("P", "CLR_BLACK"): [{"glyph": 206, "name": "black pudding"}],
    ("Q", "CLR_CYAN"): [{"glyph": 207, "name": "quantum mechanic"}],
    ("R", "CLR_BROWN"): [{"glyph": 208, "name": "rust monster"}],
    ("R", "CLR_BLUE"): [{"glyph": 209, "name": "disenchanter"}],
    ("S", "CLR_GREEN"): [{"glyph": 210, "name": "garter snake"}],
    ("S", "CLR_BROWN"): [{"glyph": 211, "name": "snake"}],
    ("S", "CLR_RED"): [{"glyph": 212, "name": "water moccasin"}],
    ("S", "CLR_MAGENTA"): [{"glyph": 213, "name": "python"}],
    ("S", "CLR_BLUE"): [
        {"glyph": 214, "name": "pit viper"},
        {"glyph": 215, "name": "cobra"},
    ],
    ("T", "CLR_BROWN"): [{"glyph": 216, "name": "troll"}],
    ("T", "CLR_WHITE"): [{"glyph": 217, "name": "ice troll"}],
    ("T", "CLR_CYAN"): [{"glyph": 218, "name": "rock troll"}],
    ("T", "CLR_BLUE"): [{"glyph": 219, "name": "water troll"}],
    ("T", "CLR_MAGENTA"): [{"glyph": 220, "name": "Olog-hai"}],
    ("U", "CLR_BROWN"): [{"glyph": 221, "name": "umber hulk"}],
    ("V", "CLR_RED"): [{"glyph": 222, "name": "vampire"}],
    ("V", "CLR_BLUE"): [{"glyph": 223, "name": "vampire lord"}],
    ("V", "CLR_MAGENTA"): [{"glyph": 224, "name": "Vlad the Impaler"}],
    ("W", "CLR_GRAY"): [{"glyph": 225, "name": "barrow wight"}],
    ("W", "CLR_BLACK"): [{"glyph": 226, "name": "wraith"}],
    ("W", "CLR_MAGENTA"): [{"glyph": 227, "name": "Nazgul"}],
    ("X", "CLR_BROWN"): [{"glyph": 228, "name": "xorn"}],
    ("Y", "CLR_GRAY"): [
        {"glyph": 229, "name": "monkey"},
        {"glyph": 234, "name": "sasquatch"},
    ],
    ("Y", "CLR_BROWN"): [
        {"glyph": 230, "name": "ape"},
        {"glyph": 231, "name": "owlbear"},
    ],
    ("Y", "CLR_WHITE"): [{"glyph": 232, "name": "yeti"}],
    ("Y", "CLR_BLACK"): [{"glyph": 233, "name": "carnivorous ape"}],
    ("Z", "CLR_BROWN"): [
        {"glyph": 235, "name": "kobold zombie"},
        {"glyph": 236, "name": "gnome zombie"},
    ],
    ("Z", "CLR_GRAY"): [{"glyph": 237, "name": "orc zombie"}],
    ("Z", "CLR_RED"): [{"glyph": 238, "name": "dwarf zombie"}],
    ("Z", "CLR_GREEN"): [{"glyph": 239, "name": "elf zombie"}],
    ("Z", "CLR_WHITE"): [
        {"glyph": 240, "name": "human zombie"},
        {"glyph": 244, "name": "skeleton"},
    ],
    ("Z", "CLR_BLUE"): [{"glyph": 241, "name": "ettin zombie"}],
    ("Z", "CLR_BLACK"): [{"glyph": 242, "name": "ghoul"}],
    ("Z", "CLR_CYAN"): [{"glyph": 243, "name": "giant zombie"}],
    ("'", "CLR_YELLOW"): [
        {"glyph": 245, "name": "straw golem"},
        {"glyph": 248, "name": "gold golem"},
    ],
    ("'", "CLR_WHITE"): [{"glyph": 246, "name": "paper golem"}],
    ("'", "CLR_BROWN"): [
        {"glyph": 247, "name": "rope golem"},
        {"glyph": 249, "name": "leather golem"},
        {"glyph": 250, "name": "wood golem"},
        {"glyph": 252, "name": "clay golem"},
    ],
    ("'", "CLR_RED"): [{"glyph": 251, "name": "flesh golem"}],
    ("'", "CLR_GRAY"): [{"glyph": 253, "name": "stone golem"}],
    ("'", "CLR_CYAN"): [
        {"glyph": 254, "name": "glass golem"},
        {"glyph": 255, "name": "iron golem"},
    ],
    ("@", "CLR_WHITE"): [
        {"glyph": 256, "name": "human"},
        {"glyph": 260, "name": "elf"},
        {"glyph": 266, "name": "doppelganger"},
        {"glyph": 267, "name": "shopkeeper"},
        {"glyph": 269, "name": "prisoner"},
        {"glyph": 271, "name": "aligned priest"},
        {"glyph": 272, "name": "high priest"},
        {"glyph": 275, "name": "nurse"},
        {"glyph": 327, "name": "archeologist"},
        {"glyph": 328, "name": "barbarian"},
        {"glyph": 329, "name": "caveman"},
        {"glyph": 330, "name": "cavewoman"},
        {"glyph": 331, "name": "healer"},
        {"glyph": 332, "name": "knight"},
        {"glyph": 333, "name": "monk"},
        {"glyph": 334, "name": "priest"},
        {"glyph": 335, "name": "priestess"},
        {"glyph": 336, "name": "ranger"},
        {"glyph": 337, "name": "rogue"},
        {"glyph": 338, "name": "samurai"},
        {"glyph": 339, "name": "tourist"},
        {"glyph": 340, "name": "valkyrie"},
        {"glyph": 341, "name": "wizard"},
        {"glyph": 348, "name": "Arch Priest"},
        {"glyph": 352, "name": "Twoflower"},
        {"glyph": 367, "name": "student"},
        {"glyph": 368, "name": "chieftain"},
        {"glyph": 369, "name": "neanderthal"},
        {"glyph": 370, "name": "attendant"},
        {"glyph": 371, "name": "page"},
        {"glyph": 372, "name": "abbot"},
        {"glyph": 373, "name": "acolyte"},
        {"glyph": 374, "name": "hunter"},
        {"glyph": 375, "name": "thug"},
        {"glyph": 376, "name": "ninja"},
        {"glyph": 377, "name": "roshi"},
        {"glyph": 378, "name": "guide"},
        {"glyph": 379, "name": "warrior"},
        {"glyph": 380, "name": "apprentice"},
    ],
    ("@", "CLR_BROWN"): [{"glyph": 257, "name": "wererat"}],
    ("@", "CLR_RED"): [
        {"glyph": 258, "name": "werejackal"},
        {"glyph": 274, "name": "sergeant"},
    ],
    ("@", "CLR_ORANGE"): [{"glyph": 259, "name": "werewolf"}],
    ("@", "CLR_GREEN"): [
        {"glyph": 261, "name": "Woodland-elf"},
        {"glyph": 276, "name": "lieutenant"},
        {"glyph": 279, "name": "watch captain"},
        {"glyph": 354, "name": "Neferet the Green"},
    ],
    ("@", "CLR_BRIGHT_GREEN"): [
        {"glyph": 262, "name": "Green-elf"},
        {"glyph": 280, "name": "Medusa"},
    ],
    ("@", "CLR_GRAY"): [
        {"glyph": 263, "name": "Grey-elf"},
        {"glyph": 273, "name": "soldier"},
        {"glyph": 278, "name": "watchman"},
    ],
    ("@", "CLR_BRIGHT_BLUE"): [
        {"glyph": 264, "name": "elf-lord"},
        {"glyph": 270, "name": "Oracle"},
    ],
    ("@", "CLR_MAGENTA"): [
        {"glyph": 265, "name": "Elvenking"},
        {"glyph": 281, "name": "Wizard of Yendor"},
        {"glyph": 282, "name": "Croesus"},
        {"glyph": 342, "name": "Lord Carnarvon"},
        {"glyph": 343, "name": "Pelias"},
        {"glyph": 344, "name": "Shaman Karnov"},
        {"glyph": 345, "name": "Hippocrates"},
        {"glyph": 346, "name": "King Arthur"},
        {"glyph": 349, "name": "Orion"},
        {"glyph": 350, "name": "Master of Thieves"},
        {"glyph": 351, "name": "Lord Sato"},
        {"glyph": 353, "name": "Norn"},
        {"glyph": 356, "name": "Thoth Amon"},
        {"glyph": 360, "name": "Master Kaen"},
        {"glyph": 363, "name": "Master Assassin"},
        {"glyph": 364, "name": "Ashikaga Takauji"},
    ],
    ("@", "CLR_BLUE"): [
        {"glyph": 268, "name": "guard"},
        {"glyph": 277, "name": "captain"},
    ],
    ("", "CLR_GRAY"): [{"glyph": 283, "name": "ghost"}],
    ("", "CLR_BLACK"): [{"glyph": 284, "name": "shade"}],
    ("&", "CLR_BLUE"): [{"glyph": 285, "name": "water demon"}],
    ("&", "CLR_GRAY"): [
        {"glyph": 286, "name": "succubus"},
        {"glyph": 288, "name": "incubus"},
        {"glyph": 294, "name": "bone devil"},
        {"glyph": 298, "name": "sandestin"},
    ],
    ("&", "CLR_BROWN"): [{"glyph": 287, "name": "horned devil"}],
    ("&", "CLR_RED"): [
        {"glyph": 289, "name": "erinys"},
        {"glyph": 290, "name": "barbed devil"},
        {"glyph": 291, "name": "marilith"},
        {"glyph": 292, "name": "vrock"},
        {"glyph": 293, "name": "hezrou"},
        {"glyph": 296, "name": "nalfeshnee"},
        {"glyph": 297, "name": "pit fiend"},
        {"glyph": 299, "name": "balrog"},
        {"glyph": 355, "name": "Minion of Huhetotl"},
        {"glyph": 361, "name": "Nalzok"},
    ],
    ("&", "CLR_WHITE"): [{"glyph": 295, "name": "ice devil"}],
    ("&", "CLR_BRIGHT_GREEN"): [{"glyph": 300, "name": "Juiblex"}],
    ("&", "CLR_MAGENTA"): [
        {"glyph": 301, "name": "Yeenoghu"},
        {"glyph": 302, "name": "Orcus"},
        {"glyph": 303, "name": "Geryon"},
        {"glyph": 304, "name": "Dispater"},
        {"glyph": 305, "name": "Baalzebub"},
        {"glyph": 306, "name": "Asmodeus"},
        {"glyph": 307, "name": "Demogorgon"},
        {"glyph": 308, "name": "Death"},
        {"glyph": 309, "name": "Pestilence"},
        {"glyph": 310, "name": "Famine"},
    ],
    ("&", "CLR_YELLOW"): [{"glyph": 311, "name": "djinni"}],
    (";", "CLR_BLUE"): [{"glyph": 312, "name": "jellyfish"}],
    (";", "CLR_RED"): [
        {"glyph": 313, "name": "piranha"},
        {"glyph": 317, "name": "kraken"},
    ],
    (";", "CLR_GRAY"): [{"glyph": 314, "name": "shark"}],
    (";", "CLR_CYAN"): [{"glyph": 315, "name": "giant eel"}],
    (";", "CLR_BRIGHT_BLUE"): [{"glyph": 316, "name": "electric eel"}],
    (":", "CLR_YELLOW"): [{"glyph": 318, "name": "newt"}],
    (":", "CLR_GREEN"): [
        {"glyph": 319, "name": "gecko"},
        {"glyph": 322, "name": "lizard"},
    ],
    (":", "CLR_BROWN"): [
        {"glyph": 320, "name": "iguana"},
        {"glyph": 321, "name": "baby crocodile"},
        {"glyph": 323, "name": "chameleon"},
        {"glyph": 324, "name": "crocodile"},
    ],
    (":", "CLR_ORANGE"): [{"glyph": 325, "name": "salamander"}],
    ("~", "CLR_BROWN"): [{"glyph": 326, "name": "long worm tail"}],
    ("@", "CLR_BLACK"): [
        {"glyph": 347, "name": "Grand Master"},
        {"glyph": 366, "name": "Dark One"},
    ],
    ("D", "CLR_MAGENTA"): [{"glyph": 357, "name": "Chromatic Dragon"}],
}

color_dict = {
    0: "CLR_BLACK",
    1: "CLR_RED",
    2: "CLR_GREEN",
    3: "CLR_BROWN",
    4: "CLR_BLUE",
    5: "CLR_MAGENTA",
    6: "CLR_CYAN",
    7: "CLR_GRAY",
    8: "NO_COLOR",
    9: "CLR_ORANGE",
    10: "CLR_BRIGHT_GREEN",
    11: "CLR_YELLOW",
    12: "CLR_BRIGHT_BLUE",
    13: "CLR_BRIGHT_MAGENTA",
    14: "CLR_BRIGHT_CYAN",
    15: "CLR_WHITE",
}

hex_to_ascii = {
    "01": "a",  # ants and similar creatures
    "02": "b",  # blobs and similar creatures
    "03": "c",  # cockatrice and similar creatures
    "04": "d",  # dogs and similar creatures
    "05": "e",  # eyes and spheres
    "06": "f",  # felines
    "07": "g",  # gremlins and gargoyles
    "08": "h",  # humanoids
    "\t": "i",  # imps and minor demons
    "\n": "j",  # jellies
    "0b": "k",  # kobolds
    "0c": "l",  # leprechauns
    "\r": "m",  # mimics
    "0e": "n",  # nymphs
    "0f": "o",  # orcs
    "10": "p",  # piercers
    "11": "q",  # quadrupeds
    "12": "r",  # rodents
    "13": "s",  # spiders and scorpions
    "14": "t",  # trappers and lurkers
    "15": "u",  # unicorns and horses
    "16": "v",  # vortices
    "17": "w",  # worms
    "18": "x",  # xan
    "19": "y",  # lights
    "1a": "z",  # zruty
    "1b": "A",  # angels and similar creatures
    "1c": "B",  # bats
    "1d": "C",  # centaurs
    "1e": "D",  # dragons
    "1f": "E",  # elementals
    " ": "F",  # fungi
    "!": "G",  # gnomes
    '"': "H",  # giants
    "23": "I",  # invisible stalkers
    "$": "J",  # jabberwocks
    "%": "K",  # Keystone Kops
    "&": "L",  # liches
    "'": "M",  # mummies
    "(": "N",  # nagas
    ")": "O",  # ogres
    "*": "P",  # puddings and oozes
    "+": "Q",  # quantum mechanics
    ",": "R",  # rust monsters and disenchanters
    "-": "S",  # snakes
    ".": "T",  # trolls
    "/": "U",  # umber hulks
    "0": "V",  # vampires
    "1": "W",  # wraiths
    "2": "X",  # xorns
    "3": "Y",  # yetis
    "4": "Z",  # zombies
    "7": "'",  # golems
    "5": "@",  # humans and elves
    "6": "",  # ghost
    "8": "&",  # demons
    "9": ";",  # sea monsters
    ":": ":",  # lizards
    ";": "~",  # long worm tail
}


# Create a dictionary from monster name to corresponding information
MONSTER_DICT = {}
for i, name, ascii, color in monsters_list:
    MONSTER_DICT[name] = {"ascii": ascii, "color": color, "glyph": i}

from collections import defaultdict

OBS_TO_GLYPH_DICT = defaultdict(list)
for glyph, name, ascii, color in monsters_list:
    OBS_TO_GLYPH_DICT[(ascii, color_dict[color])].append({"glyph": glyph, "name": name})

# print(OBS_TO_GLYPH_DICT)
